---
title: "Allen_2025b_Analysis__Figure_6B_pC1P1_subclustering"
description: description
author: "Aaron M. Allen"
date: 'Last update: `r date()`'
output:
  html_document:
    number_sections: true
    code_folding: show
    code_download: true
    theme: cerulean
    df_print: paged
    fig_width: 8.5
    fig_height: 5
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 6
---



```{css, echo = FALSE}
pre, code {white-space:pre !important; overflow-x:auto}
.tocify-item {white-space:pre}
```



```{r echo = FALSE, cache = FALSE}

```


```{r setup, echo = FALSE, cache = FALSE}
ggplot2::theme_set(ggplot2::theme_grey())
ggplot2::theme_update(panel.background = ggplot2::element_rect(fill = "transparent", colour = NA),
                      plot.background = ggplot2::element_rect(fill = "transparent", colour = NA))

rmd_name <- gsub(pattern = ".Rmd", replacement = "", x = knitr::current_input(), ignore.case = TRUE)
knitr::opts_chunk$set(dev = c("png", "cairo_pdf"),
                      dev.args=list(bg="transparent"),
                      fig.align = "center",
                      fig.height = 5,
                      fig.width = 8.5,
                      dpi = 300,
                      pdf.options(encoding = "ISOLatin9.enc"),
                      fig.path = paste0("../analyses/figures/", rmd_name, "-",
                                        format(Sys.time(), "%Y%m%d_%H%M%S"), "/"),
                      fig.retina = 1,
                      warning = TRUE,
                      message = TRUE)
```



# Setup


## Start time

```{r start-time}
set.seed(12021)
today <- format(Sys.time(), "%Y%m%d_%H%M%S")
total_start_time <- Sys.time()
total_start_time
```






## Parameters





## Libraries

```{r packages-etc, warning = FALSE, message = FALSE}

library(Seurat)
library(cowplot)
library(pheatmap)
library(colorspace)
library(tidyverse)

```



## Load Data




```{r load-meta-brain}
meta_cb <- read_rds("../../proj136/analyses/rds_files/New_Meta_cbNeuron_PUBnofacs_noPolIII_v1_alevin_LogNormalize_harmony_integrated_seurat_doublets_removed_diet.rds")
meta_cb
```



```{r}
# frudsx_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_frudsx__seu--round1_NoBatchSex.rds")
frudsx_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_frudsx__seu--round2--500VarGene--NoReg--Harmony_ori_exp_cell.rds")
frudsx_seu
```




```{r fig.width=15, fig.height=10}
DimPlot(object = frudsx_seu, 
		group.by = "RNA_snn_res.0.2",
        reduction = "tsne_20pcs", 
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed()
DimPlot(object = frudsx_seu, 
		group.by = "RNA_snn_res.1",
        reduction = "tsne_20pcs", 
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed()
DimPlot(object = frudsx_seu, 
		group.by = "RNA_snn_res.4",
        reduction = "tsne_20pcs", 
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed()
```


```{r fig.width=12, fig.height=12}

genes <- c("Fer2", "Optix", "salr", "salm", "Hr51", "otp", "dsx")
plist <- FeaturePlot(
    object = frudsx_seu, 
    reduction = "tsne_20pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 1, 
    # min.cutoff = 0,
    max.cutoff = 3,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```



```{r}
pC1_cells <- FetchData(
        object = frudsx_seu, 
        vars = c("RNA_snn_res.0.2", "RNA_snn_res.1", "RNA_snn_res.4")) %>%
    filter(RNA_snn_res.0.2 == 4) %>%
    filter(RNA_snn_res.1 %in% c(4,12)) %>%
    filter(RNA_snn_res.4 %in% c(4,21,37,43)) %>%
	rownames()
head(pC1_cells)
length(pC1_cells)
```




```{r fig.width=14, fig.height=14}

p1 <- DimPlot(object = frudsx_seu,
			  cells.highlight = pC1_cells,
			  sizes.highlight = 0.4, 
			  cols.highlight = "black", 
			  cols = "lightsteelblue2",
        reduction = "tsne_20pcs",
        pt.size = 0.4,
        raster = FALSE,
        label = FALSE,
        label.box = FALSE,
        repel = TRUE) +
    # NoAxes() +
    NoLegend() +
    coord_fixed()

# p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```
















### pC1 cells on metablob


```{r fig.width=14, fig.height=14}

p1 <- DimPlot(object = meta_cb,
			  cells.highlight = pC1_cells,
			  sizes.highlight = 0.4, 
			  cols.highlight = "black", 
			  cols = "lightsteelblue2",
        reduction = "tsne_240pcs",
        pt.size = 0.4,
        raster = FALSE,
        label = FALSE,
        label.box = FALSE,
        repel = TRUE) +
    # NoAxes() +
    NoLegend() +
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```


### achl 057 on fru/dsx


```{r}
Achl_058_cells <- FetchData(
        object = meta_cb, 
        vars = c("subcluster_clusters")) %>%
    filter(subcluster_clusters == "Achl_058") %>% 
    rownames()
head(Achl_058_cells)
length(Achl_058_cells)
```



```{r fig.width=14, fig.height=14}

p1 <- DimPlot(object = meta_cb,
			  cells.highlight = Achl_058_cells,
			  sizes.highlight = 0.4, 
			  cols.highlight = "black", 
			  cols = "lightsteelblue2",
        reduction = "tsne_240pcs",
        pt.size = 0.4,
        raster = FALSE,
        label = FALSE,
        label.box = FALSE,
        repel = TRUE) +
    # NoAxes() +
    NoLegend() +
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```


```{r fig.width=12, fig.height=12}

genes <- c("fru", "dsx")
plist <- FeaturePlot(
    object = meta_cb, 
    reduction = "tsne_240pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.6, 
    # min.cutoff = 0,
    max.cutoff = 3,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```



```{r fig.width=14, fig.height=14}

p1 <- DimPlot(object = frudsx_seu,
			  cells.highlight = Achl_058_cells,
			  sizes.highlight = 0.4, 
			  cols.highlight = "black", 
			  cols = "lightsteelblue2",
        reduction = "tsne_20pcs",
        pt.size = 0.4,
        raster = FALSE,
        label = FALSE,
        label.box = FALSE,
        repel = TRUE) +
    # NoAxes() +
    NoLegend() +
    coord_fixed()

# p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```




```{r}
length(Achl_058_cells)
length(pC1_cells)
length(unique(dplyr::union(Achl_058_cells, pC1_cells)))
length(dplyr::intersect(Achl_058_cells, pC1_cells))
length(dplyr::setdiff(Achl_058_cells, pC1_cells))
length(dplyr::setdiff(pC1_cells, Achl_058_cells))
```




```{r}
pC1p1_cells <- FetchData(
        object = meta_cb, 
        vars = c("dsx", "fru", "EGFP"),
        slot = "counts") %>%
    rownames_to_column("cell_id") %>% 
    filter(cell_id %in% unique(dplyr::union(Achl_058_cells, pC1_cells))) %>% 
    filter(fru > 0 | dsx > 0 | EGFP > 0) %>%
    pull(cell_id)
head(pC1p1_cells)
length(pC1p1_cells)
```






```{r fig.width=14, fig.height=14}

p1 <- DimPlot(object = meta_cb,
			  cells.highlight = pC1p1_cells,
			  sizes.highlight = 0.4, 
			  cols.highlight = "black", 
			  cols = "lightsteelblue2",
        reduction = "tsne_240pcs",
        pt.size = 0.4,
        raster = FALSE,
        label = FALSE,
        label.box = FALSE,
        repel = TRUE) +
    # NoAxes() +
    NoLegend() +
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```









```{r}
# pC1_sub <- subset(x = frudsx_seu, cells = pC1p1_cells)
pC1_sub <- subset(x = meta_cb, cells = pC1p1_cells)
pC1_sub
```

```{r}
pC1_list <- SplitObject(object = pC1_sub, split.by = "experiment")
pC1_list
```




```{r}
pC1_list_clean <- list()
for (i in seq_along(pC1_list)) {
    counts_to_use <- "RNA"
    pC1_list_clean[[i]] <- CreateSeuratObject(counts = pC1_list[[i]]@assays[[counts_to_use]])
	pC1_list_clean[[i]] <- AddMetaData(object = pC1_list_clean[[i]], metadata = pC1_list[[i]]$orig.ident, col.name = "orig.ident")
	pC1_list_clean[[i]] <- AddMetaData(object = pC1_list_clean[[i]], metadata = pC1_list[[i]]$experiment, col.name = "experiment")
	pC1_list_clean[[i]] <- AddMetaData(object = pC1_list_clean[[i]], metadata = pC1_list[[i]]$tissue, col.name = "tissue")
	pC1_list_clean[[i]] <- AddMetaData(object = pC1_list_clean[[i]], metadata = pC1_list[[i]]$cell_nuclei, col.name = "cell_nuclei")
	pC1_list_clean[[i]] <- AddMetaData(object = pC1_list_clean[[i]], metadata = pC1_list[[i]]$availability, col.name = "availability")
	pC1_list_clean[[i]] <- AddMetaData(object = pC1_list_clean[[i]], metadata = pC1_list[[i]]$sex, col.name = "sex")
	pC1_list_clean[[i]] <- AddMetaData(object = pC1_list_clean[[i]], metadata = pC1_list[[i]]$percent_mt, col.name = "percent_mt")
	pC1_list_clean[[i]] <- AddMetaData(object = pC1_list_clean[[i]], metadata = pC1_list[[i]]$percent_rRNA, col.name = "percent_rRNA")
	pC1_list_clean[[i]] <- AddMetaData(object = pC1_list_clean[[i]], metadata = pC1_list[[i]]$percent_rProt, col.name = "percent_rProt")
	pC1_list_clean[[i]] <- AddMetaData(object = pC1_list_clean[[i]], metadata = pC1_list[[i]]$percent_hsp, col.name = "percent_hsp")
}
names(pC1_list_clean) <- names(pC1_list)
pC1_list_clean
```





# Normalize


```{r warning=FALSE, message=FALSE}

n_var_features <- 500

for (i in seq_along(pC1_list_clean)) {
    pC1_list_clean[[i]] <- NormalizeData(object = pC1_list_clean[[i]],assay = "RNA")
    pC1_list_clean[[i]] <- FindVariableFeatures(object = pC1_list_clean[[i]],
                                                  selection.method = "mean.var.plot",     # "mean.var.plot" or "vst"
                                                  nfeatures = n_var_features,
                                                  mean.cutoff = c(0.01,Inf),
                                                  dispersion.cutoff = c(0.01, Inf))
}
```






# Integrate

```{r}
var_features <- SelectIntegrationFeatures(object.list = pC1_list_clean, nfeatures = n_var_features)
iso_genes_remove <- c("fru-plus", "fru-dP1", "fru-dP1-plus", "fruA", "fruB", "fruC",
                      "fruD1", "fruD2", "fruABint", "fruBCint", "fruCint", "fruPr1Ex1",
                      "fruPr1Ex2", "fruCOM", "dsxM", "dsxF", "dsxCOM",
                      "EGFP", "GFP", "mCherry", "Gal4", "GAL4",
                      "lncRNA:roX1", "lncRNA:roX2"
                      )
var_features <- setdiff(var_features, iso_genes_remove)
```


```{r}
pC1_seu <- merge(pC1_list_clean[[1]],
		                unlist(pC1_list_clean[2:length(pC1_list_clean)]),
		                merge.data = TRUE)

VariableFeatures(pC1_seu) <- var_features
pC1_seu
```




```{r}
FetchData(object = pC1_seu, vars = "experiment") %>% dplyr::count(experiment) %>% arrange(desc(n))
```



# Run PCA

```{r}
library(future)
# plan("multisession", workers = 8)
options(future.globals.maxSize = 8*1024*1024^2)

DefaultAssay(pC1_seu) <- "RNA"
pC1_seu <- ScaleData(
    object = pC1_seu,
    features = rownames(pC1_seu),
    assay = "RNA",
    vars.to.regress = NULL #c("experiment") #, "sex", "nCount_RNA", "percent_mt", "percent_hsp")
)
```


```{r}
# plan("multisession", workers = 8)
pC1_seu <- RunPCA(pC1_seu, features = var_features, npcs = 100, approx = FALSE)

plan("sequential")
invisible(gc())
```


# Run Harmony

```{r}
library(harmony)
pC1_seu <- RunHarmony(pC1_seu,
                    group.by.vars = c("orig.ident", "experiment", "cell_nuclei"),
					lambda = c(1,1,1),
                    assay.use = "RNA")
invisible(gc())
```








# Visualize

## Plot PCA


```{r fig.width=12, fig.height=20, warning=FALSE, message=FALSE}
library(colorspace)
library(cowplot)
p_list <- list()
for (i in 1:10) {
    p_list[[i]] <- DimHeatmap(pC1_seu,
                            reduction = "harmony",
                            dims = i,
                            cells = 500,
                            balanced = TRUE,
                            fast = FALSE) +
        scale_fill_gradientn(colors = diverging_hcl(10, palette = "Vik"))
}
plot_grid(plotlist = p_list, ncol = 2)
rm(p_list)
invisible(gc())
```


## Run UMAP



```{r}

# test_pcs <- 20
test_pcs <- seq(5, 45, 5)

for (i in seq_along(test_pcs)) {
    pC1_seu <- RunUMAP(pC1_seu, 
		                    reduction = "harmony", 
		                    dims = 1:test_pcs[[i]],
		                    n.neighbors = 50,
		                    n.epochs = 1000,
		                    min.dist = 0.01,
		                    spread = 5,
		                    fast = FALSE,
		                    verbose = TRUE,
		                    reduction.name = paste0("umap_", test_pcs[[i]], "pcs"),
		                    reduction.key = paste0("umap", test_pcs[[i]], "pcs_"))
}

pC1_seu@reductions[["umap"]] <- pC1_seu@reductions[["umap_20pcs"]]
# write_rds(x = pC1_seu, file = "../../proj136/analyses/rds_files/subclustering_pC1ish__seu--round1--500VarGene--NoReg--Harmony_ori_exp_cell.rds")
# pC1_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_pC1ish__seu--round1--500VarGene--NoReg--Harmony_ori_exp_cell.rds")

```


```{r}

for (i in seq_along(test_pcs)) {
    pC1_seu <- RunTSNE(pC1_seu,
		                    reduction = "harmony",
		                    num_threads = 24,
		                    verbose = F,
		                    dims = 1:test_pcs[[i]],
		                    do.fast = FALSE,
		                    check_duplicates = F,
		                    max_iter = 10000,
		                    theta = 0.05,
		                    reduction.name = paste0("tsne_", test_pcs[[i]], "pcs"),
		                    reduction.key = paste0("tsne", test_pcs[[i]], "pcs_"))
}

pC1_seu@reductions[["tsne"]] <- pC1_seu@reductions[["tsne_20pcs"]]
# write_rds(x = pC1_seu, file = "../../proj136/analyses/rds_files/subclustering_pC1ish__seu--round1--500VarGene--NoReg--Harmony_ori_exp_cell.rds")
# pC1_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_pC1ish__seu--round1--500VarGene--NoReg--Harmony_ori_exp_cell.rds")

```



## Plot Embeddings


```{r fig.width=8, fig.height=8}
for (test_pc in test_pcs) {
    plot(DimPlot(object = pC1_seu, reduction = paste0("umap_", test_pc, "pcs"), group.by = "experiment") + coord_fixed())
}
```



```{r fig.width=8, fig.height=8}
for (test_pc in test_pcs) {
    plot(DimPlot(object = pC1_seu, reduction = paste0("tsne_", test_pc, "pcs"), group.by = "experiment") + coord_fixed())
}
```



```{r fig.width=10, fig.height=10}
col_list <- scales::hue_pal()(length(unique(pC1_seu$experiment)))
test_pc <- 20
p <- list()
for (i in 1:length(unique(pC1_seu@meta.data[["experiment"]]))) {
  p[[i]] <- DimPlot(object = pC1_seu,
                    reduction = paste0("umap_", test_pc, "pcs"),
                    group.by = "experiment",
                    pt.size = 0.4,
                    order = c(unique(pC1_seu@meta.data[["experiment"]])[i]),
                    cols = c(rep("lightgrey",length(unique(pC1_seu$experiment)) - 1),col_list[[i]])) +
                NoLegend() +
                NoAxes() +
                coord_fixed() +
                ggtitle(unique(pC1_seu@meta.data[["experiment"]])[i])
}
plot_grid(plotlist = p, ncol = 3)
```



```{r fig.width=10, fig.height=10}
col_list <- scales::hue_pal()(length(unique(pC1_seu$experiment)))
test_pc <- 20
p <- list()
for (i in 1:length(unique(pC1_seu@meta.data[["experiment"]]))) {
    p[[i]] <- DimPlot(object = pC1_seu,
                    reduction = paste0("umap_", test_pc, "pcs"),
                    group.by = "experiment",
                    pt.size = 1,
                    order = c(unique(pC1_seu@meta.data[["experiment"]])[i]),
                    cols = c(rep("lightgrey",length(unique(pC1_seu$experiment)) - 1),col_list[[i]])) +
                NoLegend() +
                # NoAxes() +
                coord_fixed() +
                ggtitle(unique(pC1_seu@meta.data[["experiment"]])[i])
    plot(p[[i]])
}
# plot_grid(plotlist = p, ncol = 3)
```


```{r fig.width=8, fig.height=8}
col_list <- scales::hue_pal()(length(unique(pC1_seu$experiment)))
test_pc <- 20
p <- list()
for (i in 1:length(unique(pC1_seu@meta.data[["experiment"]]))) {
  p[[i]] <- DimPlot(object = pC1_seu,
                    reduction = paste0("tsne_", test_pc, "pcs"),
                    group.by = "experiment",
                    pt.size = 0.4,
                    order = c(unique(pC1_seu@meta.data[["experiment"]])[i]),
                    cols = c(rep("lightgrey",length(unique(pC1_seu$experiment)) - 1),col_list[[i]])) +
                NoLegend() +
                NoAxes() +
                coord_fixed() +
                ggtitle(unique(pC1_seu@meta.data[["experiment"]])[i])
}
plot_grid(plotlist = p, ncol = 3)
```


```{r}
FetchData(object = pC1_seu, vars = "experiment") %>% 
    dplyr::count(experiment)
```




```{r fig.width=12, fig.height=12}

genes <- c("fru", "dsx")
plist <- FeaturePlot(
    object = pC1_seu, 
    reduction = "umap_20pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 1, 
    min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```



```{r fig.width=12, fig.height=12}

genes <- c("Fer2", "Optix", "salr", "salm", "Hr51", "otp")
plist <- FeaturePlot(
    object = pC1_seu, 
    reduction = "umap_20pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 1, 
    min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```






# Clustering

```{r}
pC1_seu <- FindNeighbors(pC1_seu,
                       reduction = "harmony",
                       dims = 1:20,
                       k.param = 30,
                       force.recalc = TRUE,
                       verbose = TRUE)

# in_conda <- R.home() %>% str_detect("R4_cbrg")
# if (in_conda) {
#     algorithm_use <- 4
# } else {
    algorithm_use <- 1
# }

pC1_seu <- FindClusters(pC1_seu,
                        algorithm = algorithm_use,
                        resolution = c(0.1,0.2,0.5,1,1.5,2,3,4,5,6,8,10),
                        verbose = TRUE)
```



```{r}
write_rds(x = pC1_seu, file = "../../proj136/analyses/rds_files/subclustering_pC1ish__seu--round1--500VarGene--NoReg--Harmony_ori_exp_cell.rds")
# pC1_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_pC1ish__seu--round1--500VarGene--NoReg--Harmony_ori_exp_cell.rds")
```



```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(pC1_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = pC1_seu, group.by = res[[i]],
                           reduction = "umap_20pcs", 
                           label = FALSE, 
                           label.box = TRUE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```


```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(pC1_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = pC1_seu, group.by = res[[i]],
                           reduction = "umap_20pcs", 
                           label = TRUE, 
                           label.box = FALSE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```





```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(pC1_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = pC1_seu, group.by = res[[i]],
                           reduction = "tsne_20pcs", 
                           label = FALSE, 
                           label.box = TRUE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```




```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(pC1_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = pC1_seu, group.by = res[[i]],
                           reduction = "tsne_20pcs", 
                           label = TRUE, 
                           label.box = FALSE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```




```{r fig.width=10}
FetchData(object = pC1_seu, vars = c("experiment","RNA_snn_res.4")) %>% 
    dplyr::count(experiment, RNA_snn_res.4) %>% 
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = experiment)) +
        geom_bar(stat = "identity", position = "stack")
```



```{r fig.width=10}
FetchData(object = pC1_seu, vars = c("experiment","RNA_snn_res.4")) %>% 
    dplyr::count(experiment,RNA_snn_res.4) %>% 
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = experiment)) +
        geom_bar(stat = "identity", position = "fill")
```



```{r fig.width=10}
FetchData(object = pC1_seu, vars = c("experiment", "cell_nuclei", "RNA_snn_res.4")) %>% 
    dplyr::count(cell_nuclei, RNA_snn_res.4) %>%
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = cell_nuclei)) +
        geom_bar(stat = "identity", position = "fill") +
        geom_hline(yintercept = 0.5, colour = "white")
```



```{r fig.width=10}
FetchData(object = pC1_seu, vars = c("experiment", "sex", "RNA_snn_res.4")) %>% 
    dplyr::count(sex, RNA_snn_res.4) %>%
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = sex)) +
        geom_bar(stat = "identity", position = "fill") +
        geom_hline(yintercept = 0.5, colour = "white")
```


```{r}
FetchData(object = pC1_seu, vars = c("experiment", "sex", "RNA_snn_res.4")) %>% 
    dplyr::count(RNA_snn_res.4, sex) %>% 
    spread("sex", "n")
```





```{r}
FetchData(object = pC1_seu, vars = c("experiment", "sex", "RNA_snn_res.4")) %>% 
    dplyr::count(experiment, sex) %>% 
    spread("sex", "n")
```







# Save


```{r}
getwd()
```


```{r}
write_rds(x = pC1_seu, file = "../../proj136/analyses/rds_files/subclustering_pC1ish__seu--round1--500VarGene--NoReg--Harmony_ori_exp_cell.rds")
# pC1_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_pC1ish__seu--round1--500VarGene--NoReg--Harmony_ori_exp_cell.rds")
# pC1_seu
```








# Markers


```{r}
Idents(pC1_seu) <- "RNA_snn_res.2"
markers_pC1 <- FindAllMarkers(object = pC1_seu, assay = "RNA", test.use = "wilcox",only.pos = TRUE)
markers_pC1
```


```{r}
write_csv(x = markers_pC1, file = "../../proj136/analyses/markers/subclustering_pC1ish--round1--500VarGene--NoReg--Harmony_ori_exp_cell--RNA_snn_res_2__cluster_markers.csv")
# markers_pC1 <- read_csv(file = "../../proj136/analyses/markers/subclustering_pC1ish--round1--500VarGene--NoReg--Harmony_ori_exp_cell--RNA_snn_res_2__cluster_markers.csv")
markers_pC1
```



```{r fig.width=10, fig.height=10}
markers_pC1 %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10
DoHeatmap(pC1_seu, features = top10$gene) + 
    scale_fill_continuous_diverging(palette = "Vik", rev = FALSE,
                                    limits = c(-2,2), oob = scales::squish,
                                    na.value = "white") +
    NoLegend()
```







# Session Info

```{r}
sessionInfo()
```




