---
title: "Allen_2025a_Analysis__Figure_5F_TypeII_annotate"
description: description
author: "Aaron M. Allen"
date: 'Last update: `r date()`'
output:
  html_document:
    number_sections: true
    code_folding: show
    code_download: true
    theme: cerulean
    df_print: paged
    fig_width: 8.5
    fig_height: 5
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 6
---



```{css, echo = FALSE}
pre, code {white-space:pre !important; overflow-x:auto}
.tocify-item {white-space:pre}
```



```{r echo = FALSE, cache = FALSE}

```


```{r setup, echo = FALSE, cache = FALSE}
ggplot2::theme_set(ggplot2::theme_grey())
ggplot2::theme_update(panel.background = ggplot2::element_rect(fill = "transparent", colour = NA),
                      plot.background = ggplot2::element_rect(fill = "transparent", colour = NA))

rmd_name <- gsub(pattern = ".Rmd", replacement = "", x = knitr::current_input(), ignore.case = TRUE)
knitr::opts_chunk$set(dev = c("png", "cairo_pdf"),
                      dev.args=list(bg="transparent"),
                      fig.align = "center",
                      fig.height = 5,
                      fig.width = 8.5,
                      dpi = 300,
                      pdf.options(encoding = "ISOLatin9.enc"),
                      fig.path = paste0("../analyses/figures/", rmd_name, "-",
                                        format(Sys.time(), "%Y%m%d_%H%M%S"), "/"),
                      fig.retina = 1,
                      warning = TRUE,
                      message = TRUE)
```



# Setup


## Start time

```{r start-time}
set.seed(12021)
today <- format(Sys.time(), "%Y%m%d_%H%M%S")
total_start_time <- Sys.time()
total_start_time
```







## Libraries

```{r packages-etc, warning = FALSE, message = FALSE}
library(Seurat)
library(tidyverse)
library(cowplot)
library(colorspace)
```













## Load the data




```{r}
typeII_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_typeII__seu.rds")
typeII_seu
```




# Plots



```{r fig.width=20, fig.height=14}
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.1",
        reduction = "tsne_20pcs", 
		pt.size = 0.4,
        label = FALSE, 
        label.box = TRUE) + 
    NoLegend() + 
    coord_fixed() +
    scale_colour_discrete_qualitative("Set 2")
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.1",
        reduction = "tsne_20pcs", 
		pt.size = 0.4,
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed() +
    scale_colour_discrete_qualitative("Set 2")
```




```{r fig.width=20, fig.height=14}
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.4",
        reduction = "tsne_60pcs", 
		pt.size = 0.4,
        label = FALSE, 
        label.box = TRUE) + 
    NoLegend() + 
    coord_fixed() +
    scale_colour_discrete_qualitative("Set 2")
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.4",
        reduction = "tsne_60pcs", 
		pt.size = 0.4,
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed() +
    scale_colour_discrete_qualitative("Set 2")
```



```{r fig.width=20, fig.height=14}
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.8",
        reduction = "tsne_100pcs", 
		pt.size = 0.4,
        label = FALSE, 
        label.box = TRUE) + 
    NoLegend() + 
    coord_fixed() +
    scale_colour_discrete_qualitative("Set 2")
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.8",
        reduction = "tsne_100pcs", 
		pt.size = 0.4,
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed() +
    scale_colour_discrete_qualitative("Set 2")
```













# Cluster Markers



```{r}
cluster_markers <- read_csv(file = "../../proj136/analyses/markers/subclustering_typeII_NEW_pub_seu__RNA_snn_res.4__cluster_markers.csv") %>% 
    filter(p_val_adj < 0.05) %>% 
    filter(avg_log2FC > 0.8) %>%
    filter(pct.1 > 0.25)
```






# Cell Types




```{r fig.width=15, fig.height=14}

my_resolutions <- typeII_seu@meta.data %>% colnames() %>% str_subset("RNA_snn_res")


for (i in seq_along(my_resolutions)) {
    plot(DimPlot(object = typeII_seu, 
    		group.by = my_resolutions[[i]],
    		pt.size = 1,
            reduction = "tsne_60pcs", 
            label = TRUE, 
            label.box = FALSE) + 
        NoLegend() + 
        coord_fixed()
    )
}

```




```{r fig.width=14, fig.height=14}

genes <- c("Fer2", "Optix", "D", "Ets65A", "TfAP-2", "bsh", "odd", "Drgx", "Awh", "toy")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```


```{r fig.width=14, fig.height=14}

genes <- c("dsx", "otp", "fru")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```



```{r fig.width=14, fig.height=14}

genes <- c("dsx", "odd", "drm")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```


```{r fig.width=14, fig.height=14}

genes <- c("ple", "Mip", "Tk")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```


```{r fig.width=14, fig.height=14}

genes <- c("Ets65A", "Dh31", "sNPF")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```


```{r fig.width=14, fig.height=14}

genes <- c("Mip", "Dh31", "Dh44", "sNPF")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```



```{r fig.width=14, fig.height=14}

genes <- c("VGlut", "Tdc2", "Proc", "Dh44")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```


```{r fig.width=14, fig.height=14}

genes <- c("Nplp1", "Tk", "Dh44", "spab")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```


```{r fig.width=14, fig.height=14}

genes <- c("Vmat", "DAT", "ple", "TfAP-2", "odd")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```



```{r fig.width=14, fig.height=14}

genes <- c("Vmat", "Tdc2", "Tbh", "DAT", "ple", "SerT", "VAChT")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```

```{r fig.width=14, fig.height=14}

genes <- c("Vmat", "Tdc2", "Tbh", "DAT", "ple", "SerT", "VAChT")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```



```{r fig.width=14, fig.height=14}

genes <- c("Vmat", "Tdc2", "Tbh", "SIFa", "VAChT")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```


```{r fig.width=14, fig.height=14}

genes <- c("Vmat", "dimm")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```


```{r fig.width=20, fig.height=14}
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.0.5",
        reduction = "tsne_60pcs", 
		pt.size = 0.4,
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed()
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.4",
        reduction = "tsne_60pcs", 
		pt.size = 0.4,
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed()
```



```{r fig.width=14, fig.height=14}

DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.4",
        reduction = "tsne_60pcs", 
		pt.size = 0.4,
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed()

# genes <- c("Tk", "Mip", "SIFa", "Dh44", "Proc", "Dh31", "Ms", "sNPF", "NPF")
genes <- c("Vmat", "Tdc2", "AstC", "Dh44", "SIFa", "Ms")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```

```{r fig.width=14, fig.height=14}

DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.4",
        reduction = "tsne_60pcs", 
		pt.size = 0.4,
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed()

# genes <- c("Tk", "Mip", "SIFa", "Dh44", "Proc", "Dh31", "Ms", "sNPF", "NPF")
genes <- c("Tk", "Dh44","SIFa", "AstA")
plist <- FeaturePlot(
    object = typeII_seu, 
    reduction = "tsne_60pcs", 
    features = genes,
    combine = FALSE,
    pt.size = 0.4, 
    # min.cutoff = 0,
    # max.cutoff = 2,
    # slot = "counts",
    cols = c("lightsteelblue2", "black"), 
    raster = FALSE,
    raster.dpi = c(1024, 1024),
    order = TRUE,
    coord.fixed = TRUE
)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```

```{r}
typeII_metadata <- FetchData(object = typeII_seu, vars = c("RNA_snn_res.0.5", "RNA_snn_res.4")) %>% 
    dplyr::mutate(sub_lineage = paste0("unknown_", sprintf("%03d", as.numeric(as.character(RNA_snn_res.0.5))))) %>% 
    dplyr::mutate(cell_type = paste0("unknown_", sprintf("%03d", as.numeric(as.character(RNA_snn_res.4))))) %>% 
    
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(47), "hDeltaK", cell_type)) %>% 
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(52), "FB6E, FB7E", cell_type)) %>%                       # some differences in neuprint/codex annotations ... 
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(50), "FB2E", cell_type)) %>% 
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(98), "ExR1", cell_type)) %>% 
    
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(37), "EPG", cell_type)) %>% 
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(84), "PEG", cell_type)) %>% 
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(74), "PEN_b(PEN2)", cell_type)) %>% 
    
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(35), "PFNa", cell_type)) %>% 
    
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(75), "PFGs*", cell_type)) %>%                         # Dh31, Mip, Vmat, Tdc2 expression - same from monoamine clustering
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(10), "vDeltaM*", cell_type)) %>%                      # Mip, Dh44 expression
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(79), "PEN_a(PEN1)*", cell_type)) %>%                  # FMRFa expression
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(73), "EL*", cell_type)) %>%                           # Tdc2, Tbh, SIFa expression
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(89), "Vmat/VAChT", cell_type)) %>%                    # Vmat, Tbh, VAChT, cluster from monoamine
    
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(6), "pC1, P1", cell_type)) %>%
    dplyr::mutate(cell_type = if_else(RNA_snn_res.4 %in% c(18,27), "pC2l, pIP5", cell_type))

typeII_metadata
```

```{r}
typeII_seu <- AddMetaData(object = typeII_seu, metadata = typeII_metadata$cell_type, col.name = "cell_type")
```


```{r fig.width=20, fig.height=14}
DimPlot(object = typeII_seu, 
		group.by = "cell_type",
        reduction = "tsne_60pcs", 
		pt.size = 0.4,
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed() +
    scale_colour_discrete_qualitative("Set 2")
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.4",
        reduction = "tsne_60pcs", 
		pt.size = 0.4,
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed() +
    scale_colour_discrete_qualitative("Set 2")
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.0.5",
        reduction = "tsne_60pcs", 
		pt.size = 0.4,
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed() +
    scale_colour_discrete_qualitative("Set 2")
```


```{r}
FetchData(object = typeII_seu, vars = c("cell_type")) %>% dplyr::count(cell_type)
```


```{r}
FetchData(object = typeII_seu, vars = c("RNA_snn_res.4")) %>% dplyr::count(RNA_snn_res.4)
```


```{r}
FetchData(object = typeII_seu, vars = c("RNA_snn_res.0.5")) %>% dplyr::count(RNA_snn_res.0.5)
```



```{r fig.width=20, fig.height=14}
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.4",
        reduction = "tsne_60pcs", 
		pt.size = 0.4,
        label = FALSE, 
        label.box = TRUE) + 
    NoLegend() + 
    coord_fixed() +
    scale_colour_discrete_qualitative("Set 2")
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.4",
        reduction = "tsne_60pcs", 
		pt.size = 0.4,
        label = TRUE, 
        label.box = FALSE) + 
    NoLegend() + 
    coord_fixed() +
    scale_colour_discrete_qualitative("Set 2")
```







# colours



## clusters pseudotimed



```{r}
all_clusters <- typeII_seu@meta.data[["cell_type"]] %>% unique() #%>% sort()

cell_type_cluster_colours <- tibble(
        cluster = all_clusters,
        plot_colour = qualitative_hcl(length(all_clusters), "Set 2")
    ) %>% 
	mutate(plot_colour = if_else(str_detect(string = all_clusters, pattern = "unknown"), "grey90", plot_colour))
cell_type_cluster_colours
```


```{r plot-highlight-colour, fig.width=14, fig.height=14}
Idents(typeII_seu) <- "cell_type"

p1 <- DimPlot(
		object = typeII_seu,
		cols = cell_type_cluster_colours$plot_colour,
		reduction = "tsne_60pcs",
		pt.size = 0.4,
		raster = FALSE,
		label = FALSE,
		label.box = FALSE,
		repel = FALSE) +
    # NoAxes() +
    NoLegend() +
    coord_fixed()

# p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```




```{r plot-highlight-colour, fig.width=14, fig.height=14}
Idents(typeII_seu) <- "cell_type"

p1 <- DimPlot(
		object = typeII_seu,
		cols = cell_type_cluster_colours$plot_colour,
		reduction = "tsne_60pcs",
		pt.size = 0.4,
		raster = FALSE,
		label = TRUE,
		label.box = FALSE,
		repel = FALSE) +
    # NoAxes() +
    NoLegend() +
    coord_fixed()

# p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```



## mask cells



```{r}
typeII_metadata_mask <- FetchData(object = typeII_seu, vars = c("cell_type")) %>% 
    dplyr::mutate(cell_type_mask = cell_type) %>% 
    dplyr::mutate(cell_type_mask = if_else(cell_type == "pC1, P1", "unknown", cell_type_mask)) %>% 
    dplyr::mutate(cell_type_mask = if_else(cell_type == "pC2l, pIP5", "unknown", cell_type_mask)) %>% 
    dplyr::mutate(cell_type_mask = if_else(cell_type == "EL*", "unknown", cell_type_mask)) %>% 
    dplyr::mutate(cell_type_mask = if_else(cell_type == "PFGs*", "unknown", cell_type_mask)) %>% 
    dplyr::mutate(cell_type_mask = if_else(cell_type == "vDeltaM*", "unknown", cell_type_mask)) %>% 
    dplyr::mutate(cell_type_mask = if_else(cell_type == "PEN_a(PEN1)*", "unknown", cell_type_mask)) %>% 
    dplyr::mutate(cell_type_mask = if_else(cell_type == "Vmat/VAChT", "unknown", cell_type_mask)) %>% 
    dplyr::mutate(cell_type_mask = if_else(str_detect(string = cell_type, pattern = "unknown"), "unknown", cell_type_mask))
typeII_metadata_mask
```

```{r}
typeII_seu <- AddMetaData(object = typeII_seu, metadata = typeII_metadata_mask$cell_type_mask, col.name = "cell_type_mask")
```



```{r}
all_clusters <- typeII_seu@meta.data[["cell_type_mask"]] %>% unique() #%>% sort()

cell_type_cluster_colours <- tibble(
        cluster = all_clusters,
        plot_colour = qualitative_hcl(length(all_clusters), "Set 2")
    ) %>% 
	mutate(plot_colour = if_else(str_detect(string = all_clusters, pattern = "unknown"), "grey90", plot_colour))
cell_type_cluster_colours
```


```{r plot-highlight-colour, fig.width=14, fig.height=14}
Idents(typeII_seu) <- "cell_type_mask"

p1 <- DimPlot(
		object = typeII_seu,
		cols = cell_type_cluster_colours$plot_colour,
		reduction = "tsne_60pcs",
		pt.size = 0.4,
		raster = FALSE,
		label = FALSE,
		label.box = FALSE,
		repel = FALSE) +
    # NoAxes() +
    NoLegend() +
    coord_fixed()

# p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```












# NP genes


```{r}
np_genes <- read_tsv(file = "../../../aallen/gene_lists/gene_sets/neuropeptides.tsv", col_names = "gene")
np_genes
```





```{r}
max_umi <- apply(typeII_seu@assays$RNA@counts, 1, function(x) max(x))
max_umi <- as.data.frame(max_umi)
max_umi <- rownames_to_column(max_umi)
exp_genes <- max_umi$rowname[max_umi$max_umi>100]
exp_nps <- dplyr::intersect(exp_genes,np_genes$gene) %>% sort()
exp_nps
```




```{r}
np_cluster_makers <- cluster_markers_res4 %>% 
    filter(gene %in% np_genes$gene) %>% 
    pull(gene) %>% 
    unique() %>% 
    sort()
np_cluster_makers
```



```{r}
exp_np_markers <- dplyr::intersect(exp_nps, np_cluster_makers)
exp_np_markers
```




```{r fig.height=12, fig.width=14}

genes <- exp_np_markers
plist <- FeaturePlot(object = typeII_seu,
           reduction = "tsne_60pcs",
           features = genes,
           combine = FALSE,
           pt.size = 0.8,
		   min.cutoff = 2,
		   # max.cutoff = 4,
		   # slot = "counts",
           cols = c("lightsteelblue2", "black"),
           raster = FALSE,
           raster.dpi = c(1024, 1024),
           order = TRUE,
           coord.fixed = TRUE)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```








## heatmaps

```{r fig.width=8, fig.height=8}
avg_np <- AverageExpression(object = typeII_seu, 
                             assays = "RNA", 
                             slot = "counts",
                             features = exp_np_markers,
                             group.by = c("RNA_snn_res.4")
                             )

scaled_exp <- avg_np$RNA %>% 
    as.data.frame() %>% 
    rownames_to_column("gene") %>% 
    gather("cluster", "expression", -gene) %>% 
    spread(gene, expression) %>% 
    column_to_rownames("cluster") %>% 
    as.matrix() %>% 
    scale(center = TRUE) %>% 
    as.data.frame() %>% 
    rownames_to_column("cluster") %>% 
    gather("gene", "expression", -cluster) 
# scaled_exp

scaled_exp %>% 
    ggplot(aes(x = cluster, y = gene, fill = expression)) +
        geom_tile() +
        # scale_fill_continuous_sequential(palette = "Inferno", rev = FALSE, limits = c(0,4), oob = scales::squish) +
        scale_fill_continuous_diverging(palette = "Vik", rev = FALSE, limits = c(-2,2), oob = scales::squish) +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
              axis.title.x = element_blank()) +
		labs(caption = "slot = counts")
```



```{r fig.width=8, fig.height=8}
scaled_exp %>% 
    spread(cluster, expression) %>% 
    column_to_rownames("gene") %>% 
    pheatmap::pheatmap(.,
         breaks=seq(-2,2,0.01),
         color = diverging_hcl(401, "Vik"),
         border_color = NA,
         cluster_rows = T,
         cluster_cols = T,
         #fontsize = 16,
         angle_col = 90) 
```




```{r fig.width=8, fig.height=8}
avg_np <- AverageExpression(object = typeII_seu, 
                             assays = "RNA", 
                             slot = "data",
                             features = exp_np_markers,
                             group.by = c("RNA_snn_res.4")
                             )

scaled_exp <- avg_np$RNA %>% 
    as.data.frame() %>% 
    rownames_to_column("gene") %>% 
    gather("cluster", "expression", -gene) %>% 
    spread(gene, expression) %>% 
    column_to_rownames("cluster") %>% 
    as.matrix() %>% 
    scale(center = TRUE) %>% 
    as.data.frame() %>% 
    rownames_to_column("cluster") %>% 
    gather("gene", "expression", -cluster) 
# scaled_exp

scaled_exp %>% 
    ggplot(aes(x = cluster, y = gene, fill = expression)) +
        geom_tile() +
        # scale_fill_continuous_sequential(palette = "Inferno", rev = FALSE, limits = c(0,4), oob = scales::squish) +
        scale_fill_continuous_diverging(palette = "Vik", rev = FALSE, limits = c(-2,2), oob = scales::squish) +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
              axis.title.x = element_blank()) +
		labs(caption = "slot = data")
```



```{r fig.width=8, fig.height=8}
scaled_exp %>% 
    spread(cluster, expression) %>% 
    column_to_rownames("gene") %>% 
    pheatmap::pheatmap(.,
         breaks=seq(-2,2,0.01),
         color = diverging_hcl(401, "Vik"),
         border_color = NA,
         cluster_rows = T,
         cluster_cols = T,
         #fontsize = 16,
         angle_col = 90)
```




```{r fig.width=20, fig.height=5}
DotPlot(object = typeII_seu, features = exp_np_markers, group.by = "cell_type") +
    scale_colour_continuous_diverging(palette = "Vik", rev = FALSE, limits = c(-2,2), oob = scales::squish) + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    coord_flip()
```




```{r fig.width=8, fig.height=5}
DotPlot(object = typeII_seu, features = exp_np_markers, group.by = "cell_type_mask") +
    scale_colour_continuous_diverging(palette = "Vik", rev = FALSE, limits = c(-2,2), oob = scales::squish) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    coord_flip()
```




# add to metablob


```{r}
# meta_cb$nsc_type
```


```{r}

annotated_typeII_metadata <- FetchData(object = typeII_seu, vars = "cell_type") %>% 
    rownames_to_column("cell_id") %>% 
    mutate(cell_type = if_else(cell_type == "unknown", "Type II", cell_type)) %>% 
    mutate(cell_type = if_else(str_detect(string = cell_type, pattern = "unknown"), "Type II", cell_type))



metacb_metadata <- FetchData(object = meta_cb, vars = "nsc_type") %>% 
    rownames_to_column("cell_id") %>% 
    left_join(annotated_typeII_metadata, by  = "cell_id") %>% 
    mutate(cell_type = if_else(is.na(cell_type), "Type I", cell_type))
metacb_metadata



```





```{r}
meta_cb <- AddMetaData(object = meta_cb, metadata = metacb_metadata$cell_type, col.name = "typeII_cell_type_mask")
```



### colours



```{r}
all_clusters <- meta_cb@meta.data[["typeII_cell_type_mask"]] %>% unique() #%>% sort()

cell_type_cluster_colours <- tibble(
        cluster = all_clusters,
        plot_colour = qualitative_hcl(length(all_clusters), "Set 2")
    ) %>% 
	mutate(plot_colour = if_else(str_detect(string = all_clusters, pattern = "Type I"), "grey90", plot_colour)) %>% 
	mutate(plot_colour = if_else(str_detect(string = all_clusters, pattern = "Type II"), "grey80", plot_colour))
cell_type_cluster_colours
```


```{r plot-highlight-colour, fig.width=14, fig.height=14}
Idents(meta_cb) <- "typeII_cell_type_mask"

p1 <- DimPlot(
		object = meta_cb,
		cols = cell_type_cluster_colours$plot_colour,
		reduction = "tsne_240pcs",
		pt.size = 0.4,
		raster = FALSE,
		label = FALSE,
		label.box = FALSE,
		repel = FALSE) +
    # NoAxes() +
    NoLegend() +
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```


```{r plot-highlight-colour, fig.width=14, fig.height=14}
Idents(meta_cb) <- "typeII_cell_type_mask"

p1 <- DimPlot(
		object = meta_cb,
		cols = cell_type_cluster_colours$plot_colour,
		reduction = "tsne_240pcs",
		pt.size = 0.4,
		raster = FALSE,
		label = TRUE,
		label.box = FALSE,
		repel = FALSE) +
    # NoAxes() +
    NoLegend() +
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```



```{r}
meta_cb$typeII_cell_type_mask <- factor(meta_cb$typeII_cell_type_mask, 
                                        levels = c("EL*","EPG","ExR1","FB2E","FB6E, FB7E","hDeltaK",
                                                   "pC1, P1","pC2l, pIP5","PEG","PEN_a(PEN1)*",
                                                   "PEN_b(PEN2)","PFGs*","PFNa","vDeltaM*","Vmat/VAChT",
                                                   "Type I","Type II")
                                        )
```



```{r fig.width=20, fig.height=5}
DotPlot(object = typeII_seu, features = exp_np_markers, group.by = "cell_type") +
    scale_colour_continuous_diverging(palette = "Vik", rev = FALSE, limits = c(-2,2), oob = scales::squish) + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    coord_flip()
```





```{r fig.width=8, fig.height=6}
DotPlot(object = meta_cb, features = exp_np_markers, group.by = "typeII_cell_type_mask") +
    scale_colour_continuous_diverging(palette = "Vik", rev = FALSE, limits = c(-2,2), oob = scales::squish) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
```






```{r fig.width=30, fig.height=5}
DotPlot(object = meta_cb, features = exp_np_markers, group.by = "subcluster_clusters") +
    scale_colour_continuous_diverging(palette = "Vik", rev = FALSE, limits = c(-2,2), oob = scales::squish) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    coord_flip()
```











# Neuropeptide Receptors


```{r}
npr_genes <- read_tsv("../../../aallen/gene_lists/gene_sets/npR.tsv", col_names = "gene") %>% pull(gene) %>% sort()
npr_genes
```


```{r}
max_umi <- apply(typeII_seu@assays$RNA@counts, 1, function(x) max(x))
max_umi <- as.data.frame(max_umi)
max_umi <- rownames_to_column(max_umi)
exp_genes <- max_umi$rowname[max_umi$max_umi>5]
exp_nprs <- intersect(exp_genes,npr_genes) %>% sort()
exp_nprs
```


```{r}
Idents(typeII_seu) <- typeII_seu$RNA_snn_res.4
NPRExpByCluster <- AverageExpression(object = typeII_seu, features = exp_nprs, assays = "RNA", slot = "scale.data")
```



```{r fig.width=12, fig.height=10}
pheatmap(NPRExpByCluster$RNA,
         breaks=seq(-2,2,0.01),
         color = diverging_hcl(401, "Vik"),
         border_color = NA,
         cluster_rows = F,
         cluster_cols = F,
         treeheight_row = 100,
         treeheight_col = 100,
         fontsize = 16,
         angle_col = 90)
```



```{r fig.width=12, fig.height=10}
pheatmap(NPRExpByCluster$RNA,
         breaks=seq(-2,2,0.01),
         color = diverging_hcl(401, "Vik"),
         border_color = NA,
         cluster_rows = T,
         cluster_cols = T,
         treeheight_row = 100,
         treeheight_col = 100,
         fontsize = 16,
         angle_col = 90)
```





```{r fig.width=20, fig.height=8}
DotPlot(object = typeII_seu, features = exp_nprs, group.by = "cell_type") +
    scale_colour_continuous_diverging(palette = "Vik", rev = FALSE, limits = c(-2,2), oob = scales::squish) + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    coord_flip()
```




```{r fig.width=12, fig.height=6}
DotPlot(object = meta_cb, features = exp_nprs, group.by = "typeII_cell_type_mask") +
    scale_colour_continuous_diverging(palette = "Vik", rev = FALSE, limits = c(-2,2), oob = scales::squish) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) #+
    # coord_flip()
```






```{r fig.width=40, fig.height=8}
DotPlot(object = meta_cb, features = exp_nprs, group.by = "subcluster_clusters") +
    scale_colour_continuous_diverging(palette = "Vik", rev = FALSE, limits = c(-2,2), oob = scales::squish) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    coord_flip()
```








# other AstA-R1 clusters





```{r}
typeII_cells <- FetchData(object = meta_cb, vars = "nsc_type") %>% 
	filter(nsc_type %in% c("type_II")) %>% 
	rownames()
head(typeII_cells)
```


```{r fig.width=14, fig.height=14}
    
Idents(meta_cb) <- "subcluster_clusters"
astar1_clusters <- c("Achl_015","Achl_108","GABA_015","Glut_045","Glut_056")
for (i in seq_along(astar1_clusters)) {
    
    cells_highlight <- WhichCells(object = meta_cb, idents = astar1_clusters[[i]])
    p1 <- DimPlot(object = meta_cb,
    			  cells.highlight = cells_highlight,
    			  sizes.highlight = 0.4, 
    			  cols.highlight = "black", 
    			  cols = "lightsteelblue2",
            reduction = "tsne_240pcs",
            pt.size = 0.4,
            raster = FALSE,
            label = FALSE,
            label.box = FALSE,
            repel = TRUE) +
        NoAxes() +
        # NoLegend() +
        ggtitle(astar1_clusters[[i]])
        coord_fixed()
    
    p1[[1]]$layers[[1]]$aes_params$alpha = .1
    plot(p1)

}
    
    
```





```{r fig.height=20, fig.width=20}

genes <- c("AstA-R1")
plist <- FeaturePlot(object = meta_cb,
           reduction = "tsne_240pcs",
           features = genes,
           combine = FALSE,
           pt.size = 0.8,
		   min.cutoff = 0,
		   max.cutoff = 2,
		   # slot = "counts",
           cols = c("lightsteelblue2", "black"),
           raster = FALSE,
           raster.dpi = c(1024, 1024),
           order = TRUE,
           coord.fixed = TRUE)

for (i in seq_along(plist)) {
	plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```





```{r fig.height=20, fig.width=20}

genes <- c("AstA-R1")
plist <- FeaturePlot(object = meta_cb,
           reduction = "tsne_240pcs",
           features = genes,
           combine = FALSE,
           pt.size = 1,
		   min.cutoff = 2,
		   max.cutoff = 3,
		   slot = "counts",
           cols = c("lightsteelblue2", "black"),
           raster = FALSE,
           raster.dpi = c(1024, 1024),
           order = TRUE,
           coord.fixed = TRUE)

for (i in seq_along(plist)) {
	plist[[i]]$layers[[1]]$aes_params$alpha = .4
	plot(plist[[i]])
}

```




```{r fig.height=20, fig.width=20}

genes <- c("AstA-R1")
plist <- FeaturePlot(object = typeII_seu,
           reduction = "tsne_60pcs",
           features = genes,
           combine = FALSE,
           pt.size = 1,
		   min.cutoff = 1,
		   max.cutoff = 3,
		   # slot = "counts",
           cols = c("lightsteelblue2", "black"),
           raster = FALSE,
           raster.dpi = c(1024, 1024),
           order = TRUE,
           coord.fixed = TRUE)

for (i in seq_along(plist)) {
	# plist[[i]]$layers[[1]]$aes_params$alpha = .1
	plot(plist[[i]])
}

```











# Session info

```{r session-info}
sessionInfo()
```
