---
title: "Allen_2025a_Analysis__Figure_5D_TypeII_subclustering"
description: description
author: "Aaron M. Allen"
date: 'Last update: `r date()`'
output:
  html_document:
    number_sections: true
    code_folding: show
    code_download: true
    theme: cerulean
    df_print: paged
    fig_width: 8.5
    fig_height: 5
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 6
---



```{css, echo = FALSE}
pre, code {white-space:pre !important; overflow-x:auto}
.tocify-item {white-space:pre}
```



```{r echo = FALSE, cache = FALSE}

```


```{r setup, echo = FALSE, cache = FALSE}
ggplot2::theme_set(ggplot2::theme_grey())
ggplot2::theme_update(panel.background = ggplot2::element_rect(fill = "transparent", colour = NA),
                      plot.background = ggplot2::element_rect(fill = "transparent", colour = NA))

rmd_name <- gsub(pattern = ".Rmd", replacement = "", x = knitr::current_input(), ignore.case = TRUE)
knitr::opts_chunk$set(dev = c("png", "cairo_pdf"),
                      dev.args=list(bg="transparent"),
                      fig.align = "center",
                      fig.height = 5,
                      fig.width = 8.5,
                      dpi = 300,
                      pdf.options(encoding = "ISOLatin9.enc"),
                      fig.path = paste0("../analyses/figures/", rmd_name, "-",
                                        format(Sys.time(), "%Y%m%d_%H%M%S"), "/"),
                      fig.retina = 1,
                      warning = TRUE,
                      message = TRUE)
```



# Setup


## Start time

```{r start-time}
set.seed(12021)
today <- format(Sys.time(), "%Y%m%d_%H%M%S")
total_start_time <- Sys.time()
total_start_time
```






## Parameters





## Libraries

```{r packages-etc, warning = FALSE, message = FALSE}

library(Seurat)
library(cowplot)
library(pheatmap)
library(colorspace)
library(tidyverse)

```



## Load Data





```{r}
meta_cb <- read_rds("../../proj136/analyses/rds_files/New_Meta_cbNeuron_PUBnofacs_noPolIII_v1_alevin_LogNormalize_harmony_integrated_seurat_doublets_removed.rds")
DefaultAssay(meta_cb) <- "RNA"
Idents(meta_cb) <- "subcluster_clusters"
meta_cb
```








```{r fig.width=14, fig.height=14}


p1 <- DimPlot(object = meta_cb,
        reduction = "tsne_240pcs",
        group.by = "subcluster_clusters",
        pt.size = 0.4,
        raster = FALSE,
        label = TRUE,
        label.box = FALSE,
        repel = FALSE) +
    NoAxes() +
    NoLegend() +
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)


```



```{r fig.height=12, fig.width=20}

p1 <- DimPlot(object = meta_cb, 
		group.by = "nsc_type",
		na.value = "white",
		cols = c("#D4A2D4", "#79A2D4", "#D3A348"),
		# cols = c("#D6ABF7", "#AAD0ED", "#D9BC7D"),
		# cols = c("#e36df6", "#00b9e4", "#7798ff"),
		pt.size = 0.4,
		# alpha = 0.1,
        reduction = "tsne_240pcs", 
        label = FALSE, 
        label.box = TRUE, 
		raster = FALSE) + 
    NoLegend() + 
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```







```{r fig.height=12, fig.width=20}

p1 <- DimPlot(object = meta_cb, 
		group.by = "nsc_type",
		na.value = "white",
		cols = c("grey90", "#79A2D4", "#D3A348"),
		pt.size = 0.4,
		# alpha = 0.1,
        reduction = "tsne_240pcs", 
        label = FALSE, 
        label.box = TRUE, 
		raster = FALSE) + 
    NoLegend() + 
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```








### fix errors

```{r}
meta_cb_typeII_metadata_extrapolated <- FetchData(object = meta_cb,
                                                  vars = c("subcluster_clusters", "nsc_type")
                                                  ) %>%
    rownames_to_column("cell_id")
meta_cb_typeII_metadata_extrapolated
```


```{r}
meta_cb_typeII_metadata_extrapolated <- meta_cb_typeII_metadata_extrapolated %>%
    mutate(nsc_type = if_else(subcluster_clusters == "Achl_003", "type_I", nsc_type)) %>%
    mutate(nsc_type = if_else(subcluster_clusters == "Achl_103", "type_II", nsc_type)) %>%
    mutate(nsc_type = if_else(subcluster_clusters == "Achl_107", "type_II", nsc_type)) %>%
    mutate(nsc_type = if_else(subcluster_clusters == "Achl_090", "type_II", nsc_type)) %>%
    mutate(nsc_type = if_else(subcluster_clusters == "Glut_047", "type_II", nsc_type))
```



```{r}
meta_cb <- AddMetaData(object = meta_cb, metadata = meta_cb_typeII_metadata_extrapolated$nsc_type, col.name = "nsc_type")
```


```{r fig.height=12, fig.width=20}

p1 <- DimPlot(object = meta_cb,
		group.by = "nsc_type",
		na.value = "white",
		cols = c("#D4A2D4", "#79A2D4", "#D3A348"),
		pt.size = 0.4,
		# alpha = 0.1,
        reduction = "tsne_240pcs",
        label = FALSE,
        label.box = TRUE,
		raster = FALSE) +
    NoLegend() +
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```




```{r}
typeII_cells <- FetchData(object = meta_cb, vars = "nsc_type") %>% 
	filter(nsc_type %in% c("type_II")) %>% 
	rownames()
head(typeII_cells)
```


```{r fig.width=14, fig.height=14}

p1 <- DimPlot(object = meta_cb,
			  cells.highlight = typeII_cells,
			  sizes.highlight = 0.4, 
			  cols.highlight = "black", 
			  cols = "lightsteelblue2",
        reduction = "tsne_240pcs",
        pt.size = 0.4,
        raster = FALSE,
        label = FALSE,
        label.box = FALSE,
        repel = TRUE) +
    NoAxes() +
    NoLegend() +
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```


```{r}
typeII_sub <- subset(x = meta_cb, cells = typeII_cells)
typeII_sub
```

```{r}
typeII_list <- SplitObject(object = typeII_sub, split.by = "experiment")
typeII_list
```




```{r}
colnames(meta_cb@meta.data)
```



```{r}
typeII_list_clean <- list()
for (i in seq_along(typeII_list)) {
    counts_to_use <- "RNA"
    typeII_list_clean[[i]] <- CreateSeuratObject(counts = typeII_list[[i]]@assays[[counts_to_use]], project = names(typeII_list)[[i]])
	typeII_list_clean[[i]] <- AddMetaData(object = typeII_list_clean[[i]], metadata = typeII_list[[i]]$experiment, col.name = "experiment")
	typeII_list_clean[[i]] <- AddMetaData(object = typeII_list_clean[[i]], metadata = typeII_list[[i]]$tissue, col.name = "tissue")
	typeII_list_clean[[i]] <- AddMetaData(object = typeII_list_clean[[i]], metadata = typeII_list[[i]]$cell_nuclei, col.name = "cell_nuclei")
	typeII_list_clean[[i]] <- AddMetaData(object = typeII_list_clean[[i]], metadata = typeII_list[[i]]$availability, col.name = "availability")
	typeII_list_clean[[i]] <- AddMetaData(object = typeII_list_clean[[i]], metadata = typeII_list[[i]]$sex, col.name = "sex")
	typeII_list_clean[[i]] <- AddMetaData(object = typeII_list_clean[[i]], metadata = typeII_list[[i]]$percent_mt, col.name = "percent_mt")
	typeII_list_clean[[i]] <- AddMetaData(object = typeII_list_clean[[i]], metadata = typeII_list[[i]]$percent_rRNA, col.name = "percent_rRNA")
	typeII_list_clean[[i]] <- AddMetaData(object = typeII_list_clean[[i]], metadata = typeII_list[[i]]$percent_rProt, col.name = "percent_rProt")
	typeII_list_clean[[i]] <- AddMetaData(object = typeII_list_clean[[i]], metadata = typeII_list[[i]]$percent_hsp, col.name = "percent_hsp")
}
names(typeII_list_clean) <- names(typeII_list)
typeII_list_clean
```





```{r}
rm(meta_cb)
gc()
```







# Normalize


```{r warning=FALSE, message=FALSE}

n_var_genes <- 1000

for (i in seq_along(typeII_list_clean)) {
    typeII_list_clean[[i]] <- NormalizeData(object = typeII_list_clean[[i]],assay = "RNA")
    typeII_list_clean[[i]] <- FindVariableFeatures(object = typeII_list_clean[[i]],
                                                  selection.method = "mean.var.plot",     # "mean.var.plot" or "vst"
                                                  nfeatures = n_var_genes,
                                                  mean.cutoff = c(0.01,Inf),
                                                  dispersion.cutoff = c(0.01, Inf))
}

```






# Integrate

```{r}
var_features <- SelectIntegrationFeatures(object.list = typeII_list_clean, nfeatures = n_var_genes)
iso_genes_remove <- c("fru-plus", "fru-dP1", "fru-dP1-plus", "fruA", "fruB", "fruC",
                      "fruD1", "fruD2", "fruABint", "fruBCint", "fruCint", "fruPr1Ex1",
                      "fruPr1Ex2", "fruCOM", "dsxM", "dsxF", "dsxCOM",
                      "EGFP", "GFP", "mCherry", "Gal4", "GAL4",
                      "lncRNA:roX1", "lncRNA:roX2"
                      )
var_features <- setdiff(var_features, iso_genes_remove)
```


```{r}
typeII_seu <- merge(typeII_list_clean[[1]],
		                unlist(typeII_list_clean[2:length(typeII_list_clean)]),
		                merge.data = TRUE)

VariableFeatures(typeII_seu) <- var_features
typeII_seu
```




```{r}
FetchData(object = typeII_seu, vars = "experiment") %>% dplyr::count(experiment) %>% arrange(desc(n))
```



# Run PCA

```{r}
library(future)
# plan("multisession", workers = 8)
options(future.globals.maxSize = 8*1024*1024^2)

DefaultAssay(typeII_seu) <- "RNA"
typeII_seu <- ScaleData(object = typeII_seu,
                        assay = "RNA",
                        vars.to.regress = NULL #c("experiment") #, "sex", "nCount_RNA", "percent_mt", "percent_hsp")
                     )
```


```{r}
typeII_seu <- RunPCA(typeII_seu, features = var_features, npcs = 200, approx = FALSE)
plan("sequential")
invisible(gc())
```


# Run Harmony

```{r}

plan("multisession", workers = 8)
options(future.globals.maxSize = 8*1024*1024^2)

```



```{r}
library(harmony)
typeII_seu <- RunHarmony(typeII_seu,
                    group.by.vars = c("orig.ident", "experiment", "cell_nuclei"),
					lambda = c(1,1,1),
                    assay.use = "RNA")
invisible(gc())
```





# Visualize

## Plot PCA




```{r fig.width=12, fig.height=20, warning=FALSE, message=FALSE}
library(colorspace)
library(cowplot)
p_list <- list()
for (i in 1:10) {
    p_list[[i]] <- DimHeatmap(typeII_seu,
                            reduction = "harmony",
                            dims = i,
                            cells = 500,
                            balanced = TRUE,
                            fast = FALSE) +
        scale_fill_gradientn(colors = diverging_hcl(10, palette = "Vik"))
}
plot_grid(plotlist = p_list, ncol = 2)
rm(p_list)
invisible(gc())
```


## Run UMAP



```{r}

test_pcs <- seq(20, 100, 20)

for (i in seq_along(test_pcs)) {
    typeII_seu <- RunUMAP(typeII_seu, 
		                    reduction = "harmony", 
		                    dims = 1:test_pcs[[i]],
		                    n.neighbors = 50,
		                    n.epochs = 1000,
		                    min.dist = 0.01,
		                    spread = 5,
		                    fast = FALSE,
		                    verbose = TRUE,
		                    reduction.name = paste0("umap_", test_pcs[[i]], "pcs"),
		                    reduction.key = paste0("umap", test_pcs[[i]], "pcs_"))
}

typeII_seu@reductions[["umap"]] <- typeII_seu@reductions[["umap_60pcs"]]
write_rds(x = typeII_seu, file = "../../proj136/analyses/rds_files/subclustering_typeII__seu--round1--1000VarGene--NoReg--Harmony_ori_exp_cell.rds")

```


```{r}

# job::job({
    # plan("multisession", workers = 8)
    # options(future.globals.maxSize = 8 * 1024^3)


    for (i in seq_along(test_pcs)) {
        typeII_seu <- RunTSNE(typeII_seu,
    		                    reduction = "harmony",
    		                    num_threads = 24,
    		                    verbose = T,
    		                    dims = 1:test_pcs[[i]],
    		                    do.fast = FALSE,
    		                    check_duplicates = F,
    		                    max_iter = 10000,
    		                    theta = 0.05,
    		                    reduction.name = paste0("tsne_", test_pcs[[i]], "pcs"),
    		                    reduction.key = paste0("tsne", test_pcs[[i]], "pcs_"))
    }
    
    typeII_seu@reductions[["tsne"]] <- typeII_seu@reductions[["tsne_60pcs"]]
    write_rds(x = typeII_seu, file = "../../proj136/analyses/rds_files/subclustering_typeII__seu--round1--1000VarGene--NoReg--Harmony_ori_exp_cell.rds")


    # plan("sequential")
#     job::export(c(typeII_seu))
# }, import = c(typeII_seu, test_pcs))

```






## Plot Embeddings


```{r fig.width=8, fig.height=8}
for (test_pc in test_pcs) {
    plot(DimPlot(object = typeII_seu, reduction = paste0("umap_", test_pc, "pcs"), group.by = "experiment") + coord_fixed())
}
```



```{r fig.width=8, fig.height=8}
for (test_pc in test_pcs) {
    plot(DimPlot(object = typeII_seu, reduction = paste0("tsne_", test_pc, "pcs"), group.by = "experiment") + coord_fixed())
}
```



```{r fig.width=10, fig.height=10}
col_list <- scales::hue_pal()(length(unique(typeII_seu$experiment)))
test_pc <- 60
p <- list()
for (i in 1:length(unique(typeII_seu@meta.data[["experiment"]]))) {
  p[[i]] <- DimPlot(object = typeII_seu,
                    reduction = paste0("umap_", test_pc, "pcs"),
                    group.by = "experiment",
                    pt.size = 0.4,
                    order = c(unique(typeII_seu@meta.data[["experiment"]])[i]),
                    cols = c(rep("lightgrey",length(unique(typeII_seu$experiment)) - 1),col_list[[i]])) +
                NoLegend() +
                NoAxes() +
                coord_fixed() +
                ggtitle(unique(typeII_seu@meta.data[["experiment"]])[i])
}
plot_grid(plotlist = p, ncol = 3)
```


```{r fig.width=10, fig.height=6}
col_list <- scales::hue_pal()(length(unique(typeII_seu$sex)))
test_pc <- 60
p <- list()
for (i in 1:length(unique(typeII_seu@meta.data[["sex"]]))) {
  p[[i]] <- DimPlot(object = typeII_seu,
                    reduction = paste0("umap_", test_pc, "pcs"),
                    group.by = "sex",
                    pt.size = 0.4,
                    order = c(unique(typeII_seu@meta.data[["sex"]])[i]),
                    cols = c(rep("lightgrey",length(unique(typeII_seu$sex)) - 1),col_list[[i]])) +
                NoLegend() +
                NoAxes() +
                coord_fixed() +
                ggtitle(unique(typeII_seu@meta.data[["sex"]])[i])
}
plot_grid(plotlist = p, ncol = 2)
```


```{r fig.width=8, fig.height=8}
col_list <- scales::hue_pal()(length(unique(typeII_seu$experiment)))
test_pc <- 60
p <- list()
for (i in 1:length(unique(typeII_seu@meta.data[["experiment"]]))) {
  p[[i]] <- DimPlot(object = typeII_seu,
                    reduction = paste0("tsne_", test_pc, "pcs"),
                    group.by = "experiment",
                    pt.size = 0.4,
                    order = c(unique(typeII_seu@meta.data[["experiment"]])[i]),
                    cols = c(rep("lightgrey",length(unique(typeII_seu$experiment)) - 1),col_list[[i]])) +
                NoLegend() +
                NoAxes() +
                coord_fixed() +
                ggtitle(unique(typeII_seu@meta.data[["experiment"]])[i])
}
plot_grid(plotlist = p, ncol = 3)
```


```{r fig.width=10, fig.height=6}
col_list <- scales::hue_pal()(length(unique(typeII_seu$sex)))
test_pc <- 60
p <- list()
for (i in 1:length(unique(typeII_seu@meta.data[["sex"]]))) {
  p[[i]] <- DimPlot(object = typeII_seu,
                    reduction = paste0("tsne_", test_pc, "pcs"),
                    group.by = "sex",
                    pt.size = 0.4,
                    order = c(unique(typeII_seu@meta.data[["sex"]])[i]),
                    cols = c(rep("lightgrey",length(unique(typeII_seu$sex)) - 1),col_list[[i]])) +
                NoLegend() +
                NoAxes() +
                coord_fixed() +
                ggtitle(unique(typeII_seu@meta.data[["sex"]])[i])
}
plot_grid(plotlist = p, ncol = 2)
```

```{r}
FetchData(object = typeII_seu, vars = "experiment") %>% 
    dplyr::count(experiment)
```



# Clustering

```{r}
typeII_seu <- FindNeighbors(typeII_seu,
                       reduction = "harmony",
                       dims = 1:60,
                       k.param = 30,
                       force.recalc = TRUE,
                       verbose = TRUE)

# in_conda <- R.home() %>% str_detect("R4_cbrg")
# if (in_conda) {
#     algorithm_use <- 4
# } else {
    algorithm_use <- 1
# }

typeII_seu <- FindClusters(typeII_seu,
                        algorithm = algorithm_use,
                        resolution = c(0.1,0.2,0.5,1,1.5,2,3,4,5,6,8,10),
                        verbose = TRUE)
```



```{r}
write_rds(x = typeII_seu, file = "../../proj136/analyses/rds_files/subclustering_typeII__seu--round1--1000VarGene--NoReg--Harmony_ori_exp_cell.rds")
# typeII_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_typeII__seu--round1--1000VarGene--NoReg--Harmony_ori_exp_cell.rds")
```



```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(typeII_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = typeII_seu, group.by = res[[i]],
                           reduction = "umap_60pcs", 
                           label = FALSE, 
                           label.box = TRUE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```


```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(typeII_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = typeII_seu, group.by = res[[i]],
                           reduction = "umap_60pcs", 
                           label = TRUE, 
                           label.box = FALSE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```


```{r fig.width=15, fig.height=10}
DimPlot(object = typeII_seu, 
		group.by = "RNA_snn_res.4",
		split.by = "sex",
        reduction = "umap_60pcs", 
        label = FALSE, 
        label.box = TRUE) + 
    NoLegend() + 
    coord_fixed()
```




```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(typeII_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = typeII_seu, group.by = res[[i]],
                           reduction = "tsne_60pcs", 
                           label = TRUE, 
                           label.box = FALSE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```



```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(typeII_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = typeII_seu, group.by = res[[i]],
                           reduction = "tsne_60pcs", 
                           label = FALSE, 
                           label.box = TRUE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```





```{r fig.width=10}
FetchData(object = typeII_seu, vars = c("experiment","RNA_snn_res.4")) %>% 
    dplyr::count(experiment, RNA_snn_res.4) %>% 
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = experiment)) +
        geom_bar(stat = "identity", position = "stack")
```



```{r fig.width=10}
FetchData(object = typeII_seu, vars = c("experiment","RNA_snn_res.4")) %>% 
    dplyr::count(experiment,RNA_snn_res.4) %>% 
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = experiment)) +
        geom_bar(stat = "identity", position = "fill")
```



```{r fig.width=10}
FetchData(object = typeII_seu, vars = c("experiment", "cell_nuclei", "RNA_snn_res.4")) %>% 
    dplyr::count(cell_nuclei, RNA_snn_res.4) %>%
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = cell_nuclei)) +
        geom_bar(stat = "identity", position = "fill")
```




```{r}
FetchData(object = typeII_seu, vars = c("experiment", "sex", "RNA_snn_res.4")) %>% 
    dplyr::count(RNA_snn_res.4, sex) %>% 
    spread("sex", "n")
```





```{r}
FetchData(object = typeII_seu, vars = c("experiment", "sex", "RNA_snn_res.4")) %>% 
    dplyr::count(experiment, sex) %>% 
    spread("sex", "n")
```



```{r}
write_rds(x = typeII_seu, file = "../../proj136/analyses/rds_files/subclustering_typeII__seu--round1--1000VarGene--NoReg--Harmony_ori_exp_cell.rds")
# typeII_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_typeII__seu--round1--1000VarGene--NoReg--Harmony_ori_exp_cell.rds")
```








# Markers


```{r}

plan("sequential")
invisible(gc())

```



```{r}
Idents(typeII_seu) <- "RNA_snn_res.4"
markers_typeII <- FindAllMarkers(object = typeII_seu, assay = "RNA", test.use = "wilcox",only.pos = TRUE)
markers_typeII
```


```{r}
write_csv(x = markers_typeII, file = "../../proj136/analyses/markers/subclustering_typeII__seu--round1--1000VarGene--NoReg--Harmony_ori_exp_cell--RNA_snn_res_4__cluster_markers.csv")
markers_typeII
```



```{r fig.width=10, fig.height=10}
markers_typeII %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10
DoHeatmap(typeII_seu, features = top10$gene) +
    scale_fill_continuous_diverging(
        palette = "Vik", rev = FALSE,
        limits = c(-2,2), oob = scales::squish,
        na.value = "white"
    ) +
    NoLegend()
```











# Session Info

```{r}
sessionInfo()
```




