---
title: "Allen_2025a_Analysis__Figure_S9_OPN_Xie2021_reprocessing"
description: description
author: "Aaron M. Allen"
date: 'Last update: `r date()`'
output:
  html_document:
    number_sections: true
    code_folding: show
    code_download: true
    theme: cerulean
    df_print: paged
    fig_width: 8.5
    fig_height: 5
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 6
---



```{css, echo = FALSE}
pre, code {white-space:pre !important; overflow-x:auto}
.tocify-item {white-space:pre}
```



```{r echo = FALSE, cache = FALSE}

```


```{r setup, echo = FALSE, cache = FALSE}
ggplot2::theme_set(ggplot2::theme_grey())
ggplot2::theme_update(panel.background = ggplot2::element_rect(fill = "transparent", colour = NA),
                      plot.background = ggplot2::element_rect(fill = "transparent", colour = NA))

rmd_name <- gsub(pattern = ".Rmd", replacement = "", x = knitr::current_input(), ignore.case = TRUE)
knitr::opts_chunk$set(dev = c("png", "cairo_pdf"),
                      dev.args=list(bg="transparent"),
                      fig.align = "center",
                      fig.height = 5,
                      fig.width = 8.5,
                      dpi = 300,
                      pdf.options(encoding = "ISOLatin9.enc"),
                      fig.path = paste0("../analyses/figures/", rmd_name, "-",
                                        format(Sys.time(), "%Y%m%d_%H%M%S"), "/"),
                      fig.retina = 1,
                      warning = TRUE,
                      message = TRUE)
```



# Setup


## Start time

```{r start-time}
set.seed(12021)
today <- format(Sys.time(), "%Y%m%d_%H%M%S")
total_start_time <- Sys.time()
total_start_time
```






## Parameters





## Libraries

```{r packages-etc, warning = FALSE, message = FALSE}
library(Seurat)
library(cowplot)
library(pheatmap)
library(colorspace)
library(tidyverse)
```



## Hongie Li's OPNs


```{r}
library(SeuratDisk)
li_lab_opn <- LoadH5Seurat("../../proj108/analyses/rds_files/GSE161228_adata_all_panPN_annotated_final.h5seurat")
li_lab_opn <- UpdateSeuratObject(li_lab_opn)
li_lab_opn
```



```{r}
colnames(li_lab_opn@meta.data)
```


```{r}
li_lab_opn_adpn_sub <- subset(x = li_lab_opn, subset = lineage == "adPN")
li_lab_opn_adpn_sub
```



```{r}
adpn_li_lab_list <- SplitObject(object = li_lab_opn_adpn_sub, split.by = "batch")
adpn_li_lab_list
```



```{r}
adpn_li_lab_list_clean <- list()
for (i in seq_along(adpn_li_lab_list)) {
    counts_to_use <- "RNA"
    adpn_li_lab_list_clean[[i]] <- CreateSeuratObject(counts = adpn_li_lab_list[[i]]@assays[[counts_to_use]], project = names(adpn_li_lab_list)[[i]])
	adpn_li_lab_list_clean[[i]] <- AddMetaData(object = adpn_li_lab_list_clean[[i]], metadata = "li_lab_opn", col.name = "experiment")
	adpn_li_lab_list_clean[[i]] <- AddMetaData(object = adpn_li_lab_list_clean[[i]], metadata = "plate", col.name = "technology")
	adpn_li_lab_list_clean[[i]] <- AddMetaData(object = adpn_li_lab_list_clean[[i]], metadata = adpn_li_lab_list[[i]]$batch, col.name = "batch")
	adpn_li_lab_list_clean[[i]] <- AddMetaData(object = adpn_li_lab_list_clean[[i]], metadata = adpn_li_lab_list[[i]]$genotype, col.name = "genotype")
	adpn_li_lab_list_clean[[i]] <- AddMetaData(object = adpn_li_lab_list_clean[[i]], metadata = adpn_li_lab_list[[i]]$stage, col.name = "stage")
	adpn_li_lab_list_clean[[i]] <- AddMetaData(object = adpn_li_lab_list_clean[[i]], metadata = adpn_li_lab_list[[i]]$PN_type, col.name = "PN_type")
	adpn_li_lab_list_clean[[i]] <- AddMetaData(object = adpn_li_lab_list_clean[[i]], metadata = adpn_li_lab_list[[i]]$lineage, col.name = "lineage")
}
names(adpn_li_lab_list_clean) <- c("sample_1", "sample_2", "sample_3", "sample_4")
adpn_li_lab_list_clean[["sample_1"]] <- AddMetaData(object = adpn_li_lab_list_clean[["sample_1"]], metadata = "sample_1", col.name = "orig.ident")
adpn_li_lab_list_clean[["sample_2"]] <- AddMetaData(object = adpn_li_lab_list_clean[["sample_2"]], metadata = "sample_2", col.name = "orig.ident")
adpn_li_lab_list_clean[["sample_3"]] <- AddMetaData(object = adpn_li_lab_list_clean[["sample_3"]], metadata = "sample_3", col.name = "orig.ident")
adpn_li_lab_list_clean[["sample_4"]] <- AddMetaData(object = adpn_li_lab_list_clean[["sample_4"]], metadata = "sample_4", col.name = "orig.ident")

adpn_li_lab_list_clean
```








# Normalize



```{r warning=FALSE, message=FALSE}
for (i in seq_along(adpn_li_lab_list_clean)) {
    adpn_li_lab_list_clean[[i]] <- NormalizeData(object = adpn_li_lab_list_clean[[i]],assay = "RNA")
}
```


```{r warning=FALSE, message=FALSE}

for (i in seq_along(adpn_li_lab_list_clean)) {
    adpn_li_lab_list_clean[[i]] <- FindVariableFeatures(object = adpn_li_lab_list_clean[[i]],
                                                  selection.method = "vst",     # "mean.var.plot" or "vst"
                                                  nfeatures = 4000,
                                                  mean.cutoff = c(0.01,Inf),
                                                  dispersion.cutoff = c(0.01, Inf))
}
    
```





# Integrate

```{r}
var_features <- SelectIntegrationFeatures(object.list = adpn_li_lab_list_clean, nfeatures = 4000)
iso_genes_remove <- c("fru-plus", "fru-dP1", "fru-dP1-plus", "fruA", "fruB", "fruC",
                      "fruD1", "fruD2", "fruABint", "fruBCint", "fruCint", "fruPr1Ex1",
                      "fruPr1Ex2", "fruCOM", "dsxM", "dsxF", "dsxCOM",
                      "EGFP", "GFP", "mCherry", "Gal4", "GAL4",
                      "lncRNA:roX1", "lncRNA:roX2"
                      )
var_features <- setdiff(var_features, iso_genes_remove)
```


```{r}
adpn_seu <- merge(adpn_li_lab_list_clean[[1]],
		                unlist(adpn_li_lab_list_clean[2:length(adpn_li_lab_list_clean)]),
		                merge.data = TRUE)

VariableFeatures(adpn_seu) <- var_features
adpn_seu
```




```{r}
FetchData(object = adpn_seu, vars = "experiment") %>% dplyr::count(experiment) %>% arrange(desc(n))
```

```{r}
FetchData(object = adpn_seu, vars = "batch") %>% dplyr::count(batch) %>% arrange(desc(n))
```


# Run PCA

```{r}
library(future)
# plan("multisession", workers = 8)
options(future.globals.maxSize = 8*1024*1024^2)

DefaultAssay(adpn_seu) <- "RNA"
adpn_seu <- ScaleData(object = adpn_seu,
                        assay = "RNA",
                        vars.to.regress = c("batch", "geneotype", "nCount_RNA", "percent_mt", "percent_hsp")
                     )

adpn_seu <- RunPCA(adpn_seu, features = var_features, npcs = 100, approx = FALSE)

plan("sequential")
invisible(gc())
```


# Run Harmony


```{r}
library(harmony)
adpn_seu <- RunHarmony(adpn_seu,
                    group.by.vars = c("batch", "genotype"),
					# lambda = c(1,1),
                    assay.use = "RNA")
invisible(gc())
```








# Visualize

## Plot PCA


```{r fig.width=12, fig.height=20, warning=FALSE, message=FALSE}
library(colorspace)
library(cowplot)
p_list <- list()
for (i in 1:10) {
    p_list[[i]] <- DimHeatmap(adpn_seu,
                            reduction = "harmony",
                            dims = i,
                            cells = 500,
                            balanced = TRUE,
                            fast = FALSE) +
        scale_fill_gradientn(colors = diverging_hcl(10, palette = "Vik"))
}
plot_grid(plotlist = p_list, ncol = 2)
rm(p_list)
invisible(gc())
```


## Run UMAP



```{r}

test_pcs <- c(seq(2, 9, 1),seq(10, 18, 2),seq(20, 80, 20))



for (i in seq_along(test_pcs)) {
    adpn_seu <- RunUMAP(adpn_seu, 
		                    reduction = "harmony", 
		                    dims = 1:test_pcs[[i]],
		                    n.neighbors = 50,
		                    n.epochs = 1000,
		                    min.dist = 0.01,
		                    spread = 5,
		                    fast = FALSE,
		                    verbose = TRUE,
		                    reduction.name = paste0("umap_", test_pcs[[i]], "pcs"),
		                    reduction.key = paste0("umap", test_pcs[[i]], "pcs_"))
}


```


```{r}

for (i in seq_along(test_pcs)) {
    adpn_seu <- RunTSNE(adpn_seu,
		                    reduction = "harmony",
		                    num_threads = 24,
		                    verbose = F,
		                    dims = 1:test_pcs[[i]],
		                    do.fast = FALSE,
		                    check_duplicates = F,
		                    max_iter = 10000,
		                    theta = 0.05,
		                    reduction.name = paste0("tsne_", test_pcs[[i]], "pcs"),
		                    reduction.key = paste0("tsne", test_pcs[[i]], "pcs_"))
}

```



## Plot Embeddings


```{r fig.width=8, fig.height=8}
for (test_pc in test_pcs) {
    plot(DimPlot(object = adpn_seu, reduction = paste0("umap_", test_pc, "pcs"), group.by = "batch") + coord_fixed())
}
```


```{r fig.width=8, fig.height=8}
for (test_pc in test_pcs) {
    plot(DimPlot(object = adpn_seu, reduction = paste0("umap_", test_pc, "pcs"), group.by = "stage") + coord_fixed())
}
```


```{r fig.width=8, fig.height=8}
for (test_pc in test_pcs) {
    plot(DimPlot(object = adpn_seu, reduction = paste0("umap_", test_pc, "pcs"), group.by = "genotype") + coord_fixed())
}
```



```{r fig.width=12, fig.height=8}
for (test_pc in test_pcs) {
    plot(DimPlot(object = adpn_seu, reduction = paste0("umap_", test_pc, "pcs"), group.by = "PN_type", label = TRUE) + coord_fixed())
}
```


```{r}
pn_type_new_metadata <- FetchData(object = adpn_seu, vars = "PN_type") %>% 
    rownames_to_column("cell_id") %>% 
    mutate(PN_type_clean = PN_type) %>% 
    mutate(PN_type_clean = if_else(PN_type %in% c("nan", "APL", "DM2", "VC2"), "zzz_unknown", PN_type_clean)) %>% 
    mutate(PN_type_clean = if_else(str_detect(string = PN_type, pattern = "MARS"), "zzz_unknown", PN_type_clean))
pn_type_new_metadata
```


```{r}
adpn_seu <- AddMetaData(object = adpn_seu, metadata = pn_type_new_metadata$PN_type_clean, col.name = "PN_type_clean")
```


```{r fig.width=12, fig.height=8}
for (test_pc in test_pcs) {
    plot(DimPlot(object = adpn_seu, reduction = paste0("umap_", test_pc, "pcs"), group.by = "PN_type_clean", label = TRUE, label.box = TRUE, repel = TRUE) + coord_fixed())
}
```






```{r fig.width=20, fig.height=30}
col_list <- scales::hue_pal()(length(unique(adpn_seu$experiment)))
test_pc <- 60
p <- list()
for (i in 1:length(unique(adpn_seu@meta.data[["experiment"]]))) {
  p[[i]] <- DimPlot(object = adpn_seu,
                    reduction = paste0("umap_", test_pc, "pcs"),
                    group.by = "experiment",
                    pt.size = 0.4,
                    order = c(unique(adpn_seu@meta.data[["experiment"]])[i]),
                    cols = c(rep("lightgrey",length(unique(adpn_seu$experiment)) - 1),col_list[[i]])) +
                NoLegend() +
                NoAxes() +
                coord_fixed() +
                ggtitle(unique(adpn_seu@meta.data[["experiment"]])[i])
}
plot_grid(plotlist = p, ncol = 3)
```




```{r fig.width=8, fig.height=8}
col_list <- scales::hue_pal()(length(unique(adpn_seu$experiment)))
test_pc <- 60
p <- list()
for (i in 1:length(unique(adpn_seu@meta.data[["experiment"]]))) {
  p[[i]] <- DimPlot(object = adpn_seu,
                    reduction = paste0("tsne_", test_pc, "pcs"),
                    group.by = "experiment",
                    pt.size = 0.4,
                    order = c(unique(adpn_seu@meta.data[["experiment"]])[i]),
                    cols = c(rep("lightgrey",length(unique(adpn_seu$experiment)) - 1),col_list[[i]])) +
                NoLegend() +
                NoAxes() +
                coord_fixed() +
                ggtitle(unique(adpn_seu@meta.data[["experiment"]])[i])
}
plot_grid(plotlist = p, ncol = 3)
```


```{r}
FetchData(object = adpn_seu, vars = "experiment") %>% 
    dplyr::count(experiment)
```



```{r fig.width=16, fig.height=8}
genes <- c("nFeature_RNA","nCount_RNA")
FeaturePlot(object = adpn_seu, 
           features = genes,
           ncol = 2,
           pt.size = 0.4, 
           cols = c("lightsteelblue2", "black"),
           max.cutoff = 10000,
           reduction = "umap_60pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE)
```




```{r fig.width=15, fig.height=10}
DimPlot(object = adpn_seu, 
		group.by = "technology",
        reduction = "umap_60pcs", 
        label = FALSE, 
        label.box = TRUE) + 
    coord_fixed()
```


```{r fig.width=15, fig.height=10}
DimPlot(object = adpn_seu, 
		group.by = "technology",
		split.by = "technology",
        reduction = "umap_60pcs", 
        label = FALSE, 
        label.box = TRUE) + 
    coord_fixed()
```


```{r}
adpn_seu$lineage %>% unique()
```


```{r fig.width=15, fig.height=10}
DimPlot(object = adpn_seu, 
		group.by = "lineage",
		split.by = "technology",
        reduction = "umap_60pcs", 
        label = FALSE, 
        label.box = TRUE) + 
    coord_fixed()
```



```{r fig.width=15, fig.height=10}
DimPlot(object = adpn_seu, 
		group.by = "stage",
		split.by = "technology",
        reduction = "umap_60pcs", 
        label = FALSE, 
        label.box = TRUE) + 
    coord_fixed()
```




```{r fig.width=15, fig.height=10}
DimPlot(object = adpn_seu, 
		group.by = "genotypex",
		split.by = "technology",
        reduction = "umap_60pcs", 
        label = FALSE, 
        label.box = TRUE) + 
    coord_fixed()
```

```{r}
technology_metadata <- FetchData(object = adpn_seu, vars = "experiment") %>% 
    rownames_to_column("cell_id") %>% 
    mutate(technology = if_else(experiment == "li_lab_opn", "plate", "10x"))
adpn_seu <- AddMetaData(object = adpn_seu, metadata = technology_metadata$technology, col.name = "technology")
```





```{r fig.width=16, fig.height=8}
genes <- c("acj6", "Oaz")
FeaturePlot(object = adpn_seu, 
           features = genes,
		   # min.cutoff = 4,
           pt.size = 0.6, 
           cols = c("lightsteelblue2", "black"),
           reduction = "umap_20pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE)
```



# Clustering

```{r}
adpn_seu <- FindNeighbors(adpn_seu,
                       reduction = "harmony",
                       dims = 1:80,
                       k.param = 30,
                       force.recalc = TRUE,
                       verbose = TRUE)

in_conda <- R.home() %>% str_detect("R4_cbrg")
if (in_conda) {
    algorithm_use <- 4
} else {
    algorithm_use <- 1
}

adpn_seu <- FindClusters(adpn_seu,
                        algorithm = algorithm_use,
                        # resolution = c(0.1,0.2,0.5,1,1.5,2,3,4,5,6,8,10),
                        resolution = c(1,2,3,4,10),
                        verbose = TRUE)
```




```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(adpn_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = adpn_seu, group.by = res[[i]],
                           reduction = "umap_60pcs", 
                           label = FALSE, 
                           label.box = TRUE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```


```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(adpn_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = adpn_seu, group.by = res[[i]],
                           reduction = "umap_60pcs", 
                           label = TRUE, 
                           label.box = FALSE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```


```{r fig.width=22, fig.height=12}
DimPlot(object = adpn_seu, 
		group.by = "RNA_snn_res.4",
        reduction = "umap_60pcs", 
		split.by = "technology",
		pt.size = 1,
        label = TRUE, 
        label.box = FALSE) + 
    coord_fixed()
DimPlot(object = adpn_seu, 
		group.by = "lineage",
		split.by = "technology",
		pt.size = 1,
        reduction = "umap_60pcs", 
        label = FALSE, 
        label.box = TRUE) + 
    coord_fixed()
DimPlot(object = adpn_seu, 
		group.by = "PN_type",
        reduction = "umap_60pcs", 
		split.by = "technology",
		pt.size = 1,
        label = TRUE, 
        label.box = FALSE) + 
    coord_fixed()
```



# extrapolate lineage metadata


```{r}
adpn_seu_lineage_pn_metadata <- FetchData(object = adpn_seu, vars = c("experiment", "technology", "RNA_snn_res.4", "lineage", "PN_type")) %>% 
    rownames_to_column("cell_id")
adpn_seu_lineage_pn_metadata
```


```{r}
cluster_level_ann <- adpn_seu_lineage_pn_metadata %>% 
    select(RNA_snn_res.4, lineage) %>% 
    group_by(RNA_snn_res.4) %>%
    table() %>%
    as.data.frame() %>%
    group_by(RNA_snn_res.4) %>%
    arrange(RNA_snn_res.4, desc(Freq)) %>%
    mutate(Perc = 100 * Freq / sum(Freq)) %>%
    dplyr::slice(1)
head(cluster_level_ann)
```


```{r}
cluster_level_ann
```


```{r}
adpn_seu_lineage_pn_metadata_extrapolated <- adpn_seu_lineage_pn_metadata %>%
    select(cell_id, RNA_snn_res.4) %>% 
    left_join(select(cluster_level_ann, RNA_snn_res.4, lineage), by = "RNA_snn_res.4")
adpn_seu_lineage_pn_metadata_extrapolated
```


```{r}
adpn_seu <- AddMetaData(object = adpn_seu, metadata = adpn_seu_lineage_pn_metadata_extrapolated$lineage, col.name = "lineage")
```


```{r fig.height=12, fig.width=20}

DimPlot(object = adpn_seu, 
		group.by = "lineage",
		split.by = "technology",
		pt.size = 1,
        reduction = "umap_60pcs", 
        label = FALSE, 
        label.box = TRUE, 
		raster = FALSE) + 
    coord_fixed()

```


```{r}
adpn_seu_lineage_pn_metadata <- FetchData(object = adpn_seu, vars = c("experiment", "technology", "RNA_snn_res.10", "lineage", "PN_type")) %>% 
    rownames_to_column("cell_id")
adpn_seu_lineage_pn_metadata
```

```{r}
cluster_level_ann <- adpn_seu_lineage_pn_metadata %>% 
    select(RNA_snn_res.10, PN_type) %>% 
    group_by(RNA_snn_res.10) %>%
    table() %>%
    as.data.frame() %>%
    group_by(RNA_snn_res.10) %>%
    arrange(RNA_snn_res.10, desc(Freq)) %>%
    mutate(Perc = 100 * Freq / sum(Freq)) %>%
    dplyr::slice(1)
head(cluster_level_ann)
```


```{r}
cluster_level_ann
```


```{r}
adpn_seu_lineage_pn_metadata_extrapolated <- adpn_seu_lineage_pn_metadata %>%
    select(cell_id, RNA_snn_res.10) %>% 
    left_join(select(cluster_level_ann, RNA_snn_res.10, PN_type), by = "RNA_snn_res.10")
adpn_seu_lineage_pn_metadata_extrapolated
```




```{r}
adpn_seu <- AddMetaData(object = adpn_seu, metadata = adpn_seu_lineage_pn_metadata_extrapolated$PN_type, col.name = "PN_type")
```


```{r fig.height=12, fig.width=20}

DimPlot(object = adpn_seu, 
		group.by = "PN_type",
		split.by = "technology",
		pt.size = 1,
        reduction = "umap_60pcs", 
        label = TRUE, 
        label.box = FALSE, 
		raster = FALSE) + 
    coord_fixed()

```












```{r fig.width=20, fig.height=12}
DimPlot(object = adpn_seu, 
		group.by = "RNA_snn_res.4",
		split.by = "technology",
		pt.size = 1,
        reduction = "umap_60pcs", 
        label = TRUE, 
        label.box = FALSE) + 
    coord_fixed()
```

@1 - 0,12,5
@4 - 0,4,21,18,2,21
@10 - 0,2,4,35,36,47,18,43,1,36,44,45


```{r fig.width=20, fig.height=12}
DimPlot(object = adpn_seu, 
		group.by = "lineage",
		split.by = "technology",
		pt.size = 1,
        reduction = "umap_60pcs", 
        label = FALSE, 
        label.box = TRUE) + 
    coord_fixed()
```

```{r fig.width=20, fig.height=12}
DimPlot(object = adpn_seu, 
		group.by = "lineage",
		split.by = "technology",
		pt.size = 1,
        reduction = "umap_20pcs", 
        label = FALSE, 
        label.box = TRUE) + 
    coord_fixed()
```

```{r fig.width=20, fig.height=12}
DimPlot(object = adpn_seu, 
		group.by = "RNA_snn_res.1",
		split.by = "technology",
		pt.size = 1,
        reduction = "umap_20pcs", 
        label = TRUE, 
        label.box = FALSE) + 
    coord_fixed()
DimPlot(object = adpn_seu, 
		group.by = "RNA_snn_res.4",
		split.by = "technology",
		pt.size = 1,
        reduction = "umap_20pcs", 
        label = TRUE, 
        label.box = FALSE) + 
    coord_fixed()
```



```{r fig.width=20, fig.height=12}
DimPlot(object = adpn_seu, 
		group.by = "PN_type",
		# split.by = "technology",
		pt.size = 1,
        reduction = "umap_60pcs", 
        label = TRUE, 
        label.box = FALSE) + 
    coord_fixed()
```



```{r}
Idents(adpn_seu) <- "RNA_snn_res.4"
avg_exp <- AverageExpression(object = adpn_seu, features = c("Oaz", "acj6", "kn", "C15", "vvl", "VAChT", "VGlut", "Gad1", "Imp"), group.by = "RNA_snn_res.4", slot = "scale.data")
```

```{r}
avg_exp_df <- avg_exp$RNA %>% 
    as.data.frame() %>% 
    rownames_to_column("gene") %>% 
    gather("cluster", "expression", -gene) %>% 
    spread(gene, expression)
avg_exp_df
```


```{r}
avg_exp_df %>% 
    filter(vvl < 0) %>% 
    filter(acj6 > 0) 
```


```{r}
ALad1_clusters <- avg_exp_df %>% 
    filter(vvl < 0) %>% 
    filter(acj6 > 0) %>% 
    pull(cluster)
ALad1_clusters
```


@1 - 0,12,5
@4 - 0,4,21,18,2,21
@10 - 0,2,4,35,36,47,18,43,1,36,44,45



```{r}
filtered_cells_metadata <- FetchData(
        object = adpn_seu, 
        vars = c("technology", "nFeature_RNA", "nCount_RNA",
                "RNA_snn_res.1", "RNA_snn_res.4", "RNA_snn_res.10", 
                "lineage",
                "Oaz", "acj6", "kn", "C15", "vvl", "VAChT", "VGlut", "Gad1"),
        slot = "counts") %>% 
    rownames_to_column("cell_id") %>% 
    filter(technology == "10x") %>% 
    filter(RNA_snn_res.4 %in% ALad1_clusters) %>% 
    filter(!RNA_snn_res.1 %in% c(0,12,5)) %>% 
    filter(!RNA_snn_res.4 %in% c(0,4,21,18,2,21)) %>% 
    filter(!RNA_snn_res.10 %in% c(0,2,4,35,36,47,18,43,1,36,44,45)) %>% 
    filter(lineage == "adPN") %>% 
    filter(VGlut == 0 & Gad1 == 0) %>%
    filter(nFeature_RNA > 500) %>% 
    filter(nCount_RNA > 1000)
filtered_cells_metadata
```

```{r}
cells_to_keep <- filtered_cells_metadata %>% pull(cell_id)
```





```{r fig.width=14, fig.height=14}

p1 <- DimPlot(object = adpn_seu,
			  cells.highlight = cells_to_keep,
			  sizes.highlight = 1, 
			  cols.highlight = "black", 
			  cols = "lightsteelblue2",
        reduction = "umap_60pcs",
		split.by = "technology",
        pt.size = 1,
        raster = FALSE,
        label = FALSE,
        label.box = FALSE,
        repel = TRUE) +
    # NoAxes() +
    NoLegend() +
    coord_fixed()

# p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```





```{r}
write_csv(x = dplyr::select(filtered_cells_metadata, cell_id), file = "../../proj136/analyses/cell_lists/subclustering_ALad1_metablob_cells_to_keep--round1.rds")
```



```{r}
write_rds(x = adpn_seu, file = "../../proj136/analyses/rds_files/LiLab_reprocessing_adPN--round1.rds")
```










# Session Info

```{r}
sessionInfo()
```




