---
title: "Allen_2025a_Analysis__Figure_S13B_monoamine_subclustering"
description: description
author: "Aaron M. Allen"
date: 'Last update: `r date()`'
output:
  html_document:
    number_sections: true
    code_folding: show
    code_download: true
    theme: cerulean
    df_print: paged
    fig_width: 8.5
    fig_height: 5
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 6
---



```{css, echo = FALSE}
pre, code {white-space:pre !important; overflow-x:auto}
.tocify-item {white-space:pre}
```



```{r echo = FALSE, cache = FALSE}

```


```{r setup, echo = FALSE, cache = FALSE}
ggplot2::theme_set(ggplot2::theme_grey())
ggplot2::theme_update(panel.background = ggplot2::element_rect(fill = "transparent", colour = NA),
                      plot.background = ggplot2::element_rect(fill = "transparent", colour = NA))

rmd_name <- gsub(pattern = ".Rmd", replacement = "", x = knitr::current_input(), ignore.case = TRUE)
knitr::opts_chunk$set(dev = c("png", "cairo_pdf"),
                      dev.args=list(bg="transparent"),
                      fig.align = "center",
                      fig.height = 5,
                      fig.width = 8.5,
                      dpi = 300,
                      pdf.options(encoding = "ISOLatin9.enc"),
                      fig.path = paste0("../analyses/figures/", rmd_name, "-",
                                        format(Sys.time(), "%Y%m%d_%H%M%S"), "/"),
                      fig.retina = 1,
                      warning = TRUE,
                      message = TRUE)
```



# Setup


## Start time

```{r start-time}
set.seed(12021)
today <- format(Sys.time(), "%Y%m%d_%H%M%S")
total_start_time <- Sys.time()
total_start_time
```






## Parameters





## Libraries

```{r packages-etc, warning = FALSE, message = FALSE}
library(Seurat)
library(cowplot)
library(pheatmap)
library(colorspace)
library(tidyverse)
```



## Load Data





```{r}
meta_cb <- read_rds("../../proj136/analyses/rds_files/New_Meta_cbNeuron_PUBnofacs_noPolIII_v1_alevin_LogNormalize_harmony_integrated_seurat_doublets_removed.rds")
DefaultAssay(meta_cb) <- "RNA"
meta_cb
```











```{r fig.width=14, fig.height=14}


p1 <- DimPlot(object = meta_cb,
        reduction = "tsne_240pcs",
        group.by = "subcluster_clusters",
        pt.size = 0.4,
        raster = FALSE,
        label = TRUE,
        label.box = FALSE,
        repel = TRUE) +
    NoAxes() +
    NoLegend() +
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)


p1 <- FeaturePlot(object = meta_cb,
           features = "Vmat",
           pt.size = 0.4, 
		   min.cutoff = 2,
		   max.cutoff = 6,
           cols = c("lightsteelblue2", "black"), 
           reduction = "tsne_240pcs", 
           raster = FALSE,
           raster.dpi = c(1024, 1024),
           order = TRUE,
           coord.fixed = TRUE) +
    theme(plot.title = element_text(color="black", size=18, face="bold.italic", hjust = 0.5),
              legend.title=element_blank()
          ) + 
    NoAxes() +
    NoLegend() +
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)



```


```{r}
monoamine_cells <- FetchData(object = meta_cb, vars = "subcluster_clusters") %>% 
	filter(str_detect(string = subcluster_clusters, pattern = "Mono_")) %>% 
	rownames()
head(monoamine_cells)
```


```{r fig.width=14, fig.height=14}

p1 <- DimPlot(object = meta_cb,
			  cells.highlight = monoamine_cells,
			  sizes.highlight = 0.4, 
			  cols.highlight = "black", 
			  cols = "lightsteelblue2",
        reduction = "tsne_240pcs",
        pt.size = 0.4,
        raster = FALSE,
        label = FALSE,
        label.box = FALSE,
        repel = TRUE) +
    NoAxes() +
    NoLegend() +
    coord_fixed()

p1[[1]]$layers[[1]]$aes_params$alpha = .1
plot(p1)

```


```{r}
monoamine_sub <- subset(x = meta_cb, cells = monoamine_cells)
monoamine_sub
```

```{r}
monoamine_list <- SplitObject(object = monoamine_sub, split.by = "experiment")
monoamine_list
```





```{r}
colnames(meta_cb@meta.data)
```



```{r}
monoamine_list_clean <- list()
for (i in seq_along(monoamine_list)) {
    counts_to_use <- "RNA"
    monoamine_list_clean[[i]] <- CreateSeuratObject(counts = monoamine_list[[i]]@assays[[counts_to_use]], project = names(monoamine_list)[[i]])
	monoamine_list_clean[[i]] <- AddMetaData(object = monoamine_list_clean[[i]], metadata = monoamine_list[[i]]$orig.ident, col.name = "orig.ident")
	monoamine_list_clean[[i]] <- AddMetaData(object = monoamine_list_clean[[i]], metadata = monoamine_list[[i]]$experiment, col.name = "experiment")
	monoamine_list_clean[[i]] <- AddMetaData(object = monoamine_list_clean[[i]], metadata = monoamine_list[[i]]$tissue, col.name = "tissue")
	monoamine_list_clean[[i]] <- AddMetaData(object = monoamine_list_clean[[i]], metadata = monoamine_list[[i]]$cell_nuclei, col.name = "cell_nuclei")
	monoamine_list_clean[[i]] <- AddMetaData(object = monoamine_list_clean[[i]], metadata = monoamine_list[[i]]$availability, col.name = "availability")
	monoamine_list_clean[[i]] <- AddMetaData(object = monoamine_list_clean[[i]], metadata = monoamine_list[[i]]$sex, col.name = "sex")
	monoamine_list_clean[[i]] <- AddMetaData(object = monoamine_list_clean[[i]], metadata = monoamine_list[[i]]$percent_mt, col.name = "percent_mt")
	monoamine_list_clean[[i]] <- AddMetaData(object = monoamine_list_clean[[i]], metadata = monoamine_list[[i]]$percent_rRNA, col.name = "percent_rRNA")
	monoamine_list_clean[[i]] <- AddMetaData(object = monoamine_list_clean[[i]], metadata = monoamine_list[[i]]$percent_rProt, col.name = "percent_rProt")
	monoamine_list_clean[[i]] <- AddMetaData(object = monoamine_list_clean[[i]], metadata = monoamine_list[[i]]$percent_hsp, col.name = "percent_hsp")
}
names(monoamine_list_clean) <- names(monoamine_list)
monoamine_list_clean
```





```{r}
rm(meta_cb)
gc()
```





### Remove Low Quality Cells

```{r}

cells_remove_file <- "../../proj136/analyses/cell_lists/subclustering_monoamine_NEW_pub--round2_cells_remove.csv"

if (file.exists(cells_remove_file)) {
    cells_remove <- read_csv(file = cells_remove_file)
    for (i in seq_along(monoamine_list_clean)) {
        monoamine_list_clean[[i]] <-subset(monoamine_list_clean[[i]], cells = cells_remove$cell_id, invert = TRUE)
    }
    monoamine_list_clean
}

```





# Normalize


```{r warning=FALSE, message=FALSE}
for (i in seq_along(monoamine_list_clean)) {
    monoamine_list_clean[[i]] <- NormalizeData(object = monoamine_list_clean[[i]],assay = "RNA")
    monoamine_list_clean[[i]] <- FindVariableFeatures(object = monoamine_list_clean[[i]],
                                                  selection.method = "mean.var.plot",     # "mean.var.plot" or "vst"
                                                  nfeatures = 4000,
                                                  mean.cutoff = c(0.01,Inf),
                                                  dispersion.cutoff = c(0.01, Inf))
}
```






# Integrate

```{r}
var_features <- SelectIntegrationFeatures(object.list = monoamine_list_clean, nfeatures = 4000)
iso_genes_remove <- c("fru-plus", "fru-dP1", "fru-dP1-plus", "fruA", "fruB", "fruC",
                      "fruD1", "fruD2", "fruABint", "fruBCint", "fruCint", "fruPr1Ex1",
                      "fruPr1Ex2", "fruCOM", "dsxM", "dsxF", "dsxCOM",
                      "EGFP", "GFP", "mCherry", "Gal4", "GAL4",
                      "lncRNA:roX1", "lncRNA:roX2"
                      )
var_features <- setdiff(var_features, iso_genes_remove)
```


```{r}
monoamine_seu <- merge(monoamine_list_clean[[1]],
		                unlist(monoamine_list_clean[2:length(monoamine_list_clean)]),
		                merge.data = TRUE)

VariableFeatures(monoamine_seu) <- var_features
monoamine_seu
```




```{r}
FetchData(object = monoamine_seu, vars = "experiment") %>% dplyr::count(experiment) %>% arrange(desc(n))
```



# Run PCA

```{r}
library(future)
plan("multisession", workers = 8)
options(future.globals.maxSize = 8*1024*1024^2)

DefaultAssay(monoamine_seu) <- "RNA"
monoamine_seu <- ScaleData(object = monoamine_seu,
                        assay = "RNA",
                        vars.to.regress = c("experiment", "sex", "nCount_RNA", "percent_mt", "percent_hsp")
                     )

monoamine_seu <- RunPCA(monoamine_seu, features = var_features, npcs = 200, approx = FALSE)

plan("sequential")
invisible(gc())
```


# Run Harmony

```{r}
library(harmony)
monoamine_seu <- RunHarmony(monoamine_seu,
                    group.by.vars = c("orig.ident", "sex"),
					lambda = c(1,1),
                    assay.use = "RNA")
invisible(gc())
```








# Visualize

## Plot PCA



<!-- ```{r fig.width=8, fig.height=6} -->
<!-- ElbowPlot(monoamine_seu, reduction = "harmony", ndims = 35) + -->
<!--     geom_vline(xintercept = seq(5,35,5), linetype = "dashed", color = "grey40") + -->
<!--     ylim(0,10) -->
<!-- ``` -->




```{r fig.width=12, fig.height=20, warning=FALSE, message=FALSE}
library(colorspace)
library(cowplot)
p_list <- list()
for (i in 1:10) {
    p_list[[i]] <- DimHeatmap(monoamine_seu,
                            reduction = "harmony",
                            dims = i,
                            cells = 500,
                            balanced = TRUE,
                            fast = FALSE) +
        scale_fill_gradientn(colors = diverging_hcl(10, palette = "Vik"))
}
plot_grid(plotlist = p_list, ncol = 2)
rm(p_list)
invisible(gc())
```


## Run UMAP



```{r}

# test_pcs <- c(60)
test_pcs <- seq(10, 100, 10)

for (i in seq_along(test_pcs)) {
    monoamine_seu <- RunUMAP(monoamine_seu, 
		                    reduction = "harmony", 
		                    dims = 1:test_pcs[[i]],
		                    n.neighbors = 60,
		                    n.epochs = 1000,
		                    min.dist = 0.01,
		                    spread = 5,
		                    fast = FALSE,
		                    verbose = TRUE,
		                    reduction.name = paste0("umap_", test_pcs[[i]], "pcs"),
		                    reduction.key = paste0("umap", test_pcs[[i]], "pcs_"))
}

monoamine_seu@reductions[["umap"]] <- monoamine_seu@reductions[["umap_60pcs"]]
# write_rds(x = monoamine_seu, file = "../../proj136/analyses/rds_files/subclustering_monoamine_NEW_pub_seu--round3.rds")
# monoamine_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_monoamine_NEW_pub_seu--round3.rds")

```


```{r}

for (i in seq_along(test_pcs)) {
    monoamine_seu <- RunTSNE(monoamine_seu,
		                    reduction = "harmony",
		                    num_threads = 10,
		                    verbose = F,
		                    dims = 1:test_pcs[[i]],
		                    do.fast = FALSE,
		                    check_duplicates = F,
		                    max_iter = 10000,
		                    theta = 0.05,
		                    reduction.name = paste0("tsne_", test_pcs[[i]], "pcs"),
		                    reduction.key = paste0("tsne", test_pcs[[i]], "pcs_"))
}

monoamine_seu@reductions[["tsne"]] <- monoamine_seu@reductions[["tsne_60pcs"]]
# write_rds(x = monoamine_seu, file = "../../proj136/analyses/rds_files/subclustering_monoamine_NEW_pub_seu--round3.rds")
# monoamine_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_monoamine_NEW_pub_seu--round3.rds")

```



## Plot Embeddings


```{r fig.width=8, fig.height=8}
for (test_pc in test_pcs) {
    plot(DimPlot(object = monoamine_seu, reduction = paste0("umap_", test_pc, "pcs"), group.by = "experiment") + coord_fixed())
}
```



```{r fig.width=8, fig.height=8}
for (test_pc in test_pcs) {
    plot(DimPlot(object = monoamine_seu, reduction = paste0("tsne_", test_pc, "pcs"), group.by = "experiment") + coord_fixed())
}
```



```{r fig.width=20, fig.height=20}
col_list <- scales::hue_pal()(length(unique(monoamine_seu$experiment)))
test_pc <- 60
p <- list()
for (i in 1:length(unique(monoamine_seu@meta.data[["experiment"]]))) {
  p[[i]] <- DimPlot(object = monoamine_seu,
                    reduction = paste0("umap_", test_pc, "pcs"),
                    group.by = "experiment",
                    pt.size = 0.4,
                    order = c(unique(monoamine_seu@meta.data[["experiment"]])[i]),
                    cols = c(rep("lightgrey",length(unique(monoamine_seu$experiment)) - 1),col_list[[i]])) +
                NoLegend() +
                NoAxes() +
                coord_fixed() +
                ggtitle(unique(monoamine_seu@meta.data[["experiment"]])[i])
}
plot_grid(plotlist = p, ncol = 3)
```




```{r fig.width=20, fig.height=20}
col_list <- scales::hue_pal()(length(unique(monoamine_seu$experiment)))
test_pc <- 60
p <- list()
for (i in 1:length(unique(monoamine_seu@meta.data[["experiment"]]))) {
  p[[i]] <- DimPlot(object = monoamine_seu,
                    reduction = paste0("tsne_", test_pc, "pcs"),
                    group.by = "experiment",
                    pt.size = 0.4,
                    order = c(unique(monoamine_seu@meta.data[["experiment"]])[i]),
                    cols = c(rep("lightgrey",length(unique(monoamine_seu$experiment)) - 1),col_list[[i]])) +
                NoLegend() +
                NoAxes() +
                coord_fixed() +
                ggtitle(unique(monoamine_seu@meta.data[["experiment"]])[i])
}
plot_grid(plotlist = p, ncol = 3)
```


```{r}
FetchData(object = monoamine_seu, vars = "experiment") %>% 
    dplyr::count(experiment)
```



```{r fig.width=20, fig.height=12}
genes <- c("nFeature_RNA","nCount_RNA")
FeaturePlot(object = monoamine_seu, 
           features = genes,
           ncol = 2,
           pt.size = 0.4, 
           cols = c("lightsteelblue2", "black"),
           max.cutoff = 10000,
           reduction = "tsne_40pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE)
```



```{r fig.width=20, fig.height=12}
genes <- c("percent_hsp","percent_mt")
FeaturePlot(object = monoamine_seu, 
           features = genes,
           ncol = 2,
           pt.size = 0.4, 
           cols = c("lightsteelblue2", "black"),
           # max.cutoff = 10000,
           reduction = "tsne_40pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE)
```



```{r fig.width=20, fig.height=12}
genes <- c("Imp","dati")
FeaturePlot(object = monoamine_seu, 
           features = genes,
           ncol = 2,
           pt.size = 0.4, 
           cols = c("lightsteelblue2", "black"),
           # max.cutoff = 10000,
           reduction = "tsne_40pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE)
```



```{r fig.width=20, fig.height=12}
genes <- c("br","pdm3")
FeaturePlot(object = monoamine_seu, 
           features = genes,
           ncol = 2,
           pt.size = 0.4, 
           cols = c("lightsteelblue2", "black"),
           # max.cutoff = 10000,
           reduction = "tsne_40pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE)
```





```{r fig.width=20, fig.height=12}
genes <- c("Vmat")
FeaturePlot(object = monoamine_seu, 
           features = genes,
           split.by = "sex",
			min.cutoff = 4,
           pt.size = 1, 
           cols = c("lightsteelblue2", "black"),
           reduction = "tsne_40pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE)
```



# Clustering

```{r}
monoamine_seu <- FindNeighbors(monoamine_seu,
                       reduction = "harmony",
                       dims = 1:60,
                       k.param = 60,
                       force.recalc = TRUE,
                       verbose = TRUE)

in_conda <- R.home() %>% str_detect("R4_cbrg")
if (in_conda) {
    algorithm_use <- 4
} else {
    algorithm_use <- 1
}

monoamine_seu <- FindClusters(monoamine_seu,
                        algorithm = algorithm_use,
                        resolution = c(0.1,0.2,0.5,1,1.5,2,3,4,5,6,8,10,14,20),
                        verbose = TRUE)
```



```{r}
write_rds(x = monoamine_seu, file = "../../proj136/analyses/rds_files/subclustering_monoamine_NEW_pub_seu--round3.rds")
# monoamine_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_monoamine_NEW_pub_seu--round3.rds")
```



```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(monoamine_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = monoamine_seu, group.by = res[[i]],
                           reduction = "umap_60pcs", 
                           label = FALSE, 
                           label.box = TRUE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```


```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(monoamine_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = monoamine_seu, group.by = res[[i]],
                           reduction = "umap_60pcs", 
                           label = TRUE, 
                           label.box = FALSE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```


```{r fig.width=15, fig.height=10}
DimPlot(object = monoamine_seu, 
		group.by = "RNA_snn_res.4",
		split.by = "sex",
        reduction = "umap_60pcs", 
        label = FALSE, 
        label.box = TRUE) + 
    NoLegend() + 
    coord_fixed()
```




```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(monoamine_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = monoamine_seu, group.by = res[[i]],
                           reduction = "tsne_60pcs", 
                           label = TRUE, 
                           label.box = FALSE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```



```{r fig.width=12, fig.height=26}
p_list <- list()
res <- colnames(monoamine_seu@meta.data) %>% str_subset("RNA_snn_res") %>% head(n = 10)
for (i in seq_along(res)) {
    p_list[[i]] <- DimPlot(object = monoamine_seu, group.by = res[[i]],
                           reduction = "tsne_60pcs", 
                           label = FALSE, 
                           label.box = TRUE) + 
        NoLegend() + 
        coord_fixed()
}
plot_grid(plotlist = p_list,  ncol = 2)
```





```{r fig.width=10}
FetchData(object = monoamine_seu, vars = c("experiment","RNA_snn_res.4")) %>% 
    dplyr::count(experiment, RNA_snn_res.4) %>% 
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = experiment)) +
        geom_bar(stat = "identity", position = "stack")
```




```{r fig.width=18, fig.height=18}
DimPlot(object = monoamine_seu,reduction = "umap_40pcs", pt.size = 1, group.by = "RNA_snn_res.4", label = TRUE, label.box = FALSE) + coord_fixed()
DimPlot(object = monoamine_seu,reduction = "tsne_40pcs", pt.size = 1, group.by = "RNA_snn_res.4", label = TRUE, label.box = FALSE) + coord_fixed()
```


```{r fig.width=14}
FetchData(object = monoamine_seu, vars = c("experiment","RNA_snn_res.4")) %>% 
    dplyr::count(experiment,RNA_snn_res.4) %>% 
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = experiment)) +
        geom_bar(stat = "identity", position = "fill") #+
        #geom_hline(yintercept = 0.5, colour = "white")
```



```{r fig.width=14}
FetchData(object = monoamine_seu, vars = c("experiment", "cell_nuclei", "RNA_snn_res.4")) %>% 
    dplyr::count(cell_nuclei, RNA_snn_res.4) %>%
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = cell_nuclei)) +
        geom_bar(stat = "identity", position = "fill") +
        geom_hline(yintercept = 0.5, colour = "white")
```


```{r fig.width=14}
FetchData(object = monoamine_seu, vars = c("experiment", "tissue", "RNA_snn_res.4")) %>% 
    dplyr::count(tissue, RNA_snn_res.4) %>%
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = tissue)) +
        geom_bar(stat = "identity", position = "fill") +
        geom_hline(yintercept = 0.5, colour = "white")
```


```{r fig.width=14}
FetchData(object = monoamine_seu, vars = c("experiment", "sex", "RNA_snn_res.4")) %>% 
    dplyr::count(sex, RNA_snn_res.4) %>%
    ggplot(aes(x = RNA_snn_res.4, y = n, fill = sex)) +
        geom_bar(stat = "identity", position = "fill") +
        geom_hline(yintercept = 0.5, colour = "white")
```


```{r fig.width=18, fig.height=18}
DimPlot(object = monoamine_seu,reduction = "umap_40pcs", pt.size = 1, group.by = "RNA_snn_res.10", label = TRUE, label.box = FALSE) + coord_fixed()
DimPlot(object = monoamine_seu,reduction = "tsne_40pcs", pt.size = 1, group.by = "RNA_snn_res.10", label = TRUE, label.box = FALSE) + coord_fixed()
```



```{r fig.width=14}
FetchData(object = monoamine_seu, vars = c("experiment","RNA_snn_res.10")) %>% 
    dplyr::count(experiment,RNA_snn_res.10) %>% 
    ggplot(aes(x = RNA_snn_res.10, y = n, fill = experiment)) +
        geom_bar(stat = "identity", position = "fill") #+
        #geom_hline(yintercept = 0.5, colour = "white")
```




```{r fig.width=14}
FetchData(object = monoamine_seu, vars = c("experiment", "cell_nuclei", "RNA_snn_res.10")) %>% 
    dplyr::count(cell_nuclei, RNA_snn_res.10) %>%
    ggplot(aes(x = RNA_snn_res.10, y = n, fill = cell_nuclei)) +
        geom_bar(stat = "identity", position = "fill") +
        geom_hline(yintercept = 0.5, colour = "white")
```


```{r fig.width=14}
FetchData(object = monoamine_seu, vars = c("experiment", "tissue", "RNA_snn_res.10")) %>% 
    dplyr::count(tissue, RNA_snn_res.10) %>%
    ggplot(aes(x = RNA_snn_res.10, y = n, fill = tissue)) +
        geom_bar(stat = "identity", position = "fill") +
        geom_hline(yintercept = 0.5, colour = "white")
```













```{r}
FetchData(object = monoamine_seu, vars = c("experiment", "sex", "RNA_snn_res.4")) %>% 
    dplyr::count(RNA_snn_res.4, sex) %>% 
    spread("sex", "n")
```





```{r}
FetchData(object = monoamine_seu, vars = c("experiment", "sex", "RNA_snn_res.4")) %>% 
    dplyr::count(experiment, sex) %>% 
    spread("sex", "n")
```






# Candidate Genes



```{r fig.width=10, fig.height=10}
genes <- c("SerT")
DimPlot(object = monoamine_seu, 
        group.by = "RNA_snn_res.10",
        pt.size = 1,
       reduction = "tsne_30pcs", 
       label = TRUE, 
       label.box = FALSE,
       repel = FALSE) + 
    NoLegend() + 
    coord_fixed()
FeaturePlot(object = monoamine_seu, 
           features = genes,
           ncol = 1,
           pt.size = 0.4, 
           cols = c("lightsteelblue2", "black"), 
           reduction = "tsne_30pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE) + 
    NoLegend()
```


```{r fig.width=10, fig.height=10}
genes <- c("Tbh")
DimPlot(object = monoamine_seu, 
        group.by = "RNA_snn_res.4",
        pt.size = 1,
       reduction = "tsne_30pcs", 
       label = TRUE, 
       label.box = FALSE,
       repel = TRUE) + 
    NoLegend() + 
    coord_fixed()
FeaturePlot(object = monoamine_seu, 
           features = genes,
           ncol = 1,
           pt.size = 0.4, 
           cols = c("lightsteelblue2", "black"), 
           reduction = "tsne_30pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE) + 
    NoLegend()
```



```{r fig.width=10, fig.height=10}
genes <- c("Tdc2")
DimPlot(object = monoamine_seu, 
        group.by = "RNA_snn_res.4",
        pt.size = 1,
       reduction = "tsne_30pcs", 
       label = TRUE, 
       label.box = FALSE,
       repel = TRUE) + 
    NoLegend() + 
    coord_fixed()
FeaturePlot(object = monoamine_seu, 
           features = genes,
           ncol = 1,
           pt.size = 0.4, 
           cols = c("lightsteelblue2", "black"), 
           reduction = "tsne_30pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE) + 
    NoLegend()
```



```{r fig.width=10, fig.height=10}
genes <- c("Hdc")
DimPlot(object = monoamine_seu, 
        group.by = "RNA_snn_res.10",
        pt.size = 1,
       reduction = "tsne_30pcs", 
       label = TRUE, 
       label.box = FALSE,
       repel = TRUE) + 
    NoLegend() + 
    coord_fixed()
FeaturePlot(object = monoamine_seu, 
           features = genes,
           ncol = 1,
           pt.size = 0.4, 
           cols = c("lightsteelblue2", "black"), 
           reduction = "tsne_30pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE) + 
    NoLegend()
```

```{r fig.width=10, fig.height=10}
genes <- c("DAT")
DimPlot(object = monoamine_seu, 
        group.by = "RNA_snn_res.4",
        pt.size = 1,
       reduction = "tsne_30pcs", 
       label = TRUE, 
       label.box = FALSE,
       repel = TRUE) + 
    NoLegend() + 
    coord_fixed()
FeaturePlot(object = monoamine_seu, 
           features = genes,
           ncol = 1,
           pt.size = 0.4, 
           cols = c("lightsteelblue2", "black"), 
           reduction = "tsne_30pcs", 
           raster = FALSE, 
           order = TRUE,
           coord.fixed = TRUE) + 
    NoLegend()
```


<!-- ```{r} -->
<!-- cell_type_broad_metadata <- FetchData(object = mono_seu, vars = c("RNA_snn_res.4", "RNA_snn_res.10")) %>%  -->
<!--     rownames_to_column("cell_id") %>%  -->
<!--     mutate(cell_type_broad = "unknown") %>%  -->
<!--     mutate(cell_type_broad = if_else(RNA_snn_res.10 %in% c(46,34,50,39,26,33), "Ser", cell_type_broad)) %>%  -->
<!--     mutate(cell_type_broad = if_else(RNA_snn_res.4 %in% c(13,15), "Oct", cell_type_broad)) %>%  -->
<!--     mutate(cell_type_broad = if_else(RNA_snn_res.4 %in% c(9,18,27,30,40), "Tyr", cell_type_broad)) %>%  -->
<!--     mutate(cell_type_broad = if_else(RNA_snn_res.10 %in% c(45,21,40,44,46,34,32,38,36,14,28,31,32,42,17,6,47,41,20,43,30,42,6), "Dop", cell_type_broad)) %>% -->
<!--     mutate(cell_type_broad = if_else(RNA_snn_res.4 %in% c(20,23,3,4,10,7,1,8,6,16,11,14,24), "PAM", cell_type_broad)) %>%  -->
<!--     mutate(cell_type_broad = if_else(RNA_snn_res.10 %in% c(8), "His_Dop_mix", cell_type_broad)) -->
<!-- cell_type_broad_metadata -->
<!-- ``` -->


<!-- ```{r} -->
<!-- mono_seu <- AddMetaData(object = mono_seu, metadata = cell_type_broad_metadata$cell_type_broad , col.name = "cell_type_broad") -->
<!-- ``` -->


<!-- ```{r fig.width=10, fig.height=10} -->
<!-- DimPlot(object = mono_seu,  -->
<!--         group.by = "cell_type_broad", -->
<!--         pt.size = 1, -->
<!--        reduction = "tsne_30pcs",  -->
<!--        label = FALSE,  -->
<!--        label.box = FALSE, -->
<!--        repel = FALSE) +  -->
<!--     # NoLegend() +  -->
<!--     coord_fixed() -->
<!-- ``` -->




# Markers


<!-- ```{r} -->
<!-- Idents(monoamine_seu) <- "RNA_snn_res.4" -->
<!-- markers_endo <- FindAllMarkers(object = monoamine_seu, assay = "RNA", test.use = "wilcox",only.pos = TRUE) -->
<!-- markers_endo -->
<!-- ``` -->



<!-- ```{r fig.width=10, fig.height=10} -->
<!-- markers_endo %>% -->
<!--     group_by(cluster) %>% -->
<!--     dplyr::filter(avg_log2FC > 1) %>% -->
<!--     slice_head(n = 10) %>% -->
<!--     ungroup() -> top10 -->
<!-- DoHeatmap(monoamine_seu, features = top10$gene) + NoLegend() -->
<!-- ``` -->








```{r}
write_rds(x = monoamine_seu, file = "../../proj136/analyses/rds_files/subclustering_monoamine_NEW_pub_seu--round3.rds")
# monoamine_seu <- read_rds("../../proj136/analyses/rds_files/subclustering_monoamine_NEW_pub_seu--round3.rds")
```














# Session Info

```{r}
sessionInfo()
```




